/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "eidos/service.proto" (package "ttab.eidos", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Tagger } from "./service";
import type { RegisterUsageResponse } from "./service";
import type { RegisterUsageRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AnalyseDocumentResponse } from "./service";
import type { AnalyseDocumentRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ttab.eidos.Tagger
 */
export interface ITaggerClient {
    /**
     * AnalyseDocument and return the generated meta document and the text
     * representatin of the document that was used for analysis.
     *
     * @generated from protobuf rpc: AnalyseDocument
     */
    analyseDocument(input: AnalyseDocumentRequest, options?: RpcOptions): UnaryCall<AnalyseDocumentRequest, AnalyseDocumentResponse>;
    /**
     * RegisterUsage is used to inform eidos when an external system has tagged a
     * piece of media with entities managed by eidos.
     *
     * @generated from protobuf rpc: RegisterUsage
     */
    registerUsage(input: RegisterUsageRequest, options?: RpcOptions): UnaryCall<RegisterUsageRequest, RegisterUsageResponse>;
}
/**
 * @generated from protobuf service ttab.eidos.Tagger
 */
export class TaggerClient implements ITaggerClient, ServiceInfo {
    typeName = Tagger.typeName;
    methods = Tagger.methods;
    options = Tagger.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * AnalyseDocument and return the generated meta document and the text
     * representatin of the document that was used for analysis.
     *
     * @generated from protobuf rpc: AnalyseDocument
     */
    analyseDocument(input: AnalyseDocumentRequest, options?: RpcOptions): UnaryCall<AnalyseDocumentRequest, AnalyseDocumentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AnalyseDocumentRequest, AnalyseDocumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RegisterUsage is used to inform eidos when an external system has tagged a
     * piece of media with entities managed by eidos.
     *
     * @generated from protobuf rpc: RegisterUsage
     */
    registerUsage(input: RegisterUsageRequest, options?: RpcOptions): UnaryCall<RegisterUsageRequest, RegisterUsageResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterUsageRequest, RegisterUsageResponse>("unary", this._transport, method, opt, input);
    }
}
