/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "eidos/service.proto" (package "ttab.eidos", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Document } from "../newsdoc/newsdoc";
/**
 * @generated from protobuf message ttab.eidos.AnalyseDocumentRequest
 */
export interface AnalyseDocumentRequest {
    /**
     * DocumentUUID is the uuid of the document to analyse, optional. Required if
     * no document is provided in the request.
     *
     * @generated from protobuf field: string document_uuid = 1
     */
    documentUuid: string;
    /**
     * Document to analyse, optional.
     *
     * @generated from protobuf field: newsdoc.Document document = 2
     */
    document?: Document;
}
/**
 * @generated from protobuf message ttab.eidos.AnalyseDocumentResponse
 */
export interface AnalyseDocumentResponse {
    /**
     * Meta document with the detected entities and topics.
     *
     * @generated from protobuf field: newsdoc.Document meta = 1
     */
    meta?: Document;
    /**
     * Text used in recognition query.
     *
     * @generated from protobuf field: string text = 2
     */
    text: string;
}
/**
 * @generated from protobuf message ttab.eidos.RegisterUsageRequest
 */
export interface RegisterUsageRequest {
    /**
     * ContentType of the media that was tagged.
     *
     * @generated from protobuf field: string content_type = 1
     */
    contentType: string;
    /**
     * ContentURI is an URI that identified the tagged media.
     *
     * @generated from protobuf field: string context_uri = 2
     */
    contextUri: string;
    /**
     * The UUIDs of the entities that were used.
     *
     * @generated from protobuf field: repeated string entity_uuids = 3
     */
    entityUuids: string[];
}
/**
 * @generated from protobuf message ttab.eidos.RegisterUsageResponse
 */
export interface RegisterUsageResponse {
}
// @generated message type with reflection information, may provide speed optimized methods
class AnalyseDocumentRequest$Type extends MessageType<AnalyseDocumentRequest> {
    constructor() {
        super("ttab.eidos.AnalyseDocumentRequest", [
            { no: 1, name: "document_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "document", kind: "message", T: () => Document }
        ]);
    }
    create(value?: PartialMessage<AnalyseDocumentRequest>): AnalyseDocumentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.documentUuid = "";
        if (value !== undefined)
            reflectionMergePartial<AnalyseDocumentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnalyseDocumentRequest): AnalyseDocumentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string document_uuid */ 1:
                    message.documentUuid = reader.string();
                    break;
                case /* newsdoc.Document document */ 2:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnalyseDocumentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string document_uuid = 1; */
        if (message.documentUuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.documentUuid);
        /* newsdoc.Document document = 2; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.eidos.AnalyseDocumentRequest
 */
export const AnalyseDocumentRequest = new AnalyseDocumentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AnalyseDocumentResponse$Type extends MessageType<AnalyseDocumentResponse> {
    constructor() {
        super("ttab.eidos.AnalyseDocumentResponse", [
            { no: 1, name: "meta", kind: "message", T: () => Document },
            { no: 2, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AnalyseDocumentResponse>): AnalyseDocumentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<AnalyseDocumentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnalyseDocumentResponse): AnalyseDocumentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* newsdoc.Document meta */ 1:
                    message.meta = Document.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* string text */ 2:
                    message.text = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnalyseDocumentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* newsdoc.Document meta = 1; */
        if (message.meta)
            Document.internalBinaryWrite(message.meta, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string text = 2; */
        if (message.text !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.text);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.eidos.AnalyseDocumentResponse
 */
export const AnalyseDocumentResponse = new AnalyseDocumentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterUsageRequest$Type extends MessageType<RegisterUsageRequest> {
    constructor() {
        super("ttab.eidos.RegisterUsageRequest", [
            { no: 1, name: "content_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "context_uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "entity_uuids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterUsageRequest>): RegisterUsageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.contentType = "";
        message.contextUri = "";
        message.entityUuids = [];
        if (value !== undefined)
            reflectionMergePartial<RegisterUsageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterUsageRequest): RegisterUsageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string content_type */ 1:
                    message.contentType = reader.string();
                    break;
                case /* string context_uri */ 2:
                    message.contextUri = reader.string();
                    break;
                case /* repeated string entity_uuids */ 3:
                    message.entityUuids.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterUsageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string content_type = 1; */
        if (message.contentType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.contentType);
        /* string context_uri = 2; */
        if (message.contextUri !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.contextUri);
        /* repeated string entity_uuids = 3; */
        for (let i = 0; i < message.entityUuids.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.entityUuids[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.eidos.RegisterUsageRequest
 */
export const RegisterUsageRequest = new RegisterUsageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterUsageResponse$Type extends MessageType<RegisterUsageResponse> {
    constructor() {
        super("ttab.eidos.RegisterUsageResponse", []);
    }
    create(value?: PartialMessage<RegisterUsageResponse>): RegisterUsageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RegisterUsageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterUsageResponse): RegisterUsageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterUsageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.eidos.RegisterUsageResponse
 */
export const RegisterUsageResponse = new RegisterUsageResponse$Type();
/**
 * @generated ServiceType for protobuf service ttab.eidos.Tagger
 */
export const Tagger = new ServiceType("ttab.eidos.Tagger", [
    { name: "AnalyseDocument", options: {}, I: AnalyseDocumentRequest, O: AnalyseDocumentResponse },
    { name: "RegisterUsage", options: {}, I: RegisterUsageRequest, O: RegisterUsageResponse }
]);
