/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "ntb/service.proto" (package "ttab.ntb", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ttab.ntb.GetAssignmentRequest
 */
export interface GetAssignmentRequest {
    /**
     * The assignee is identified by their commission code.
     *
     * @generated from protobuf field: string commission_code = 1
     */
    commissionCode: string;
}
/**
 * @generated from protobuf message ttab.ntb.GetAssignmentResponse
 */
export interface GetAssignmentResponse {
    /**
     * @generated from protobuf field: string planning_uuid = 1
     */
    planningUuid: string;
    /**
     * @generated from protobuf field: string assignment_uuid = 2
     */
    assignmentUuid: string;
}
// Request/Response Messages

/**
 * @generated from protobuf message ttab.ntb.GetItemRequest
 */
export interface GetItemRequest {
    /**
     * Archive to search in.
     *
     * @generated from protobuf field: string archive = 1
     */
    archive: string;
    /**
     * ID of the item to get.
     *
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message ttab.ntb.GetItemResponse
 */
export interface GetItemResponse {
    /**
     * @generated from protobuf field: ttab.ntb.MediaItem item = 1
     */
    item?: MediaItem;
}
/**
 * @generated from protobuf message ttab.ntb.SearchRequest
 */
export interface SearchRequest {
    /**
     * Archive to search in.
     *
     * @generated from protobuf field: string archive = 1
     */
    archive: string;
    /**
     * Search limit, max 200, default: 50.
     *
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * Offset - search offset, max 10000, default: 0.
     *
     * @generated from protobuf field: int32 offset = 3
     */
    offset: number;
    /**
     * Sort options to the list.
     *
     * @generated from protobuf field: ttab.ntb.Sort sort = 4
     */
    sort?: Sort;
    /**
     * Query - freetext query.
     *
     * @generated from protobuf field: string query = 5
     */
    query: string;
    /**
     * ItemId - filter by the itemId.
     *
     * @generated from protobuf field: string item_id = 6
     */
    itemId: string;
    /**
     * City filter.
     *
     * @generated from protobuf field: string city = 7
     */
    city: string;
    /**
     * Country filter.
     *
     * @generated from protobuf field: string country = 8
     */
    country: string;
    /**
     * Creator filter (photographer).
     *
     * @generated from protobuf field: string creator = 9
     */
    creator: string;
    /**
     * Ids filters by asset ids.
     *
     * @generated from protobuf field: repeated string ids = 10
     */
    ids: string[];
    /**
     * Keywords filter.
     *
     * @generated from protobuf field: repeated string keywords = 11
     */
    keywords: string[];
    /**
     * Filter on collections.
     *
     * @generated from protobuf field: repeated int32 collections = 12
     */
    collections: number[];
    /**
     * Filter on albums.
     *
     * @generated from protobuf field: repeated int32 albums = 13
     */
    albums: number[];
    /**
     * Filter on categories.
     *
     * @generated from protobuf field: repeated string categories = 14
     */
    categories: string[];
    /**
     * Include/exclude assets based on location.
     *
     * @generated from protobuf field: string locations = 15
     */
    locations: string;
    /**
     * Filter on jobId.
     *
     * @generated from protobuf field: string job_id = 16
     */
    jobId: string;
    /**
     * Filter on image orientation.
     *
     * @generated from protobuf field: ttab.ntb.Orientation orientation = 17
     */
    orientation: Orientation;
    /**
     * View results after this point in list.
     *
     * @generated from protobuf field: repeated string search_after = 18
     */
    searchAfter: string[];
    /**
     * Filter on origins.
     *
     * @generated from protobuf field: repeated ttab.ntb.Origin origins = 19
     */
    origins: Origin[];
    /**
     * Filter on file type.
     *
     * @generated from protobuf field: ttab.ntb.FileType file_type = 20
     */
    fileType: FileType;
    /**
     * Get assets created on and after the RFC3339 timestamp.
     *
     * @generated from protobuf field: string created_min = 21
     */
    createdMin: string;
    /**
     * Get assets created on and before the RFC3339 timestamp.
     *
     * @generated from protobuf field: string created_max = 22
     */
    createdMax: string;
    /**
     * Set to true to search against items outside of your subscription agreement.
     *
     * @generated from protobuf field: bool outside_subscription = 23
     */
    outsideSubscription: boolean;
}
/**
 * @generated from protobuf message ttab.ntb.Sort
 */
export interface Sort {
    /**
     * @generated from protobuf field: string field = 1
     */
    field: string;
    /**
     * @generated from protobuf field: bool descending = 2
     */
    descending: boolean;
}
/**
 * @generated from protobuf message ttab.ntb.SearchResponse
 */
export interface SearchResponse {
    /**
     * @generated from protobuf field: ttab.ntb.Page page = 1
     */
    page?: Page;
    /**
     * @generated from protobuf field: repeated ttab.ntb.MediaItem data = 3
     */
    data: MediaItem[];
}
/**
 * @generated from protobuf message ttab.ntb.Page
 */
export interface Page {
    /**
     * @generated from protobuf field: int32 offset = 1
     */
    offset: number;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * @generated from protobuf field: int32 count = 3
     */
    count: number;
    /**
     * @generated from protobuf field: int32 total = 4
     */
    total: number;
    /**
     * SearchAfter can be used for pagination in search results.
     *
     * @generated from protobuf field: repeated string search_after = 5
     */
    searchAfter: string[];
}
// Media Types

/**
 * @generated from protobuf message ttab.ntb.MediaItem
 */
export interface MediaItem {
    /**
     * ID of the item.
     *
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * Type is the content type.
     *
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * Archive (mb/ntb/tt).
     *
     * @generated from protobuf field: string archive = 3
     */
    archive: string;
    /**
     * UserID is the user ID of user who uploaded the media.
     *
     * @generated from protobuf field: string user_id = 4
     */
    userId: string;
    /**
     * Restrictions indicates whether there are any restrictions noted on the
     * media.
     *
     * @generated from protobuf field: bool restrictions = 5
     */
    restrictions: boolean;
    /**
     * Headline is a brief synopsis of the caption. Corresponds to IPTC field.
     *
     * @generated from protobuf field: string headline = 6
     */
    headline: string;
    /**
     * Description is a textual description, including captions, of the media.
     *
     * @generated from protobuf field: string description = 7
     */
    description: string;
    /**
     * AltTextAccessibility is a textual description for accessibility.
     *
     * @generated from protobuf field: string alt_text_accessibility = 8
     */
    altTextAccessibility: string;
    /**
     * Creator contains the name of the photographer or company/org.
     *
     * @generated from protobuf field: string creator = 9
     */
    creator: string;
    /**
     * Keywords to express the subject of the image.
     *
     * @generated from protobuf field: repeated string keywords = 10
     */
    keywords: string[];
    /**
     * Category corresponds to IPTC category field.
     *
     * @generated from protobuf field: string category = 11
     */
    category: string;
    /**
     * PersonsShown are persons in the image.
     *
     * @generated from protobuf field: repeated ttab.ntb.Person persons_shown = 12
     */
    personsShown: Person[];
    /**
     * ImageRating is the rating of the image by its user or supplier (0-5).
     * Using optional to distinguish between unset and 0.
     *
     * @generated from protobuf field: optional int32 image_rating = 13
     */
    imageRating?: number;
    /**
     * Title provides a short human-readable name.
     *
     * @generated from protobuf field: string title = 14
     */
    title: string;
    /**
     * DateArchived designates the date and time the content was archived.
     *
     * @generated from protobuf field: string date_archived = 15
     */
    dateArchived: string;
    /**
     * DateCreated designates the date and time the content was created. Not
     * present if the source data is invalid or missing.
     *
     * @generated from protobuf field: ttab.ntb.ImpreciseTimestamp date_created = 16
     */
    dateCreated?: ImpreciseTimestamp;
    /**
     * Country corresponds to IPTC field.
     *
     * @generated from protobuf field: string country = 17
     */
    country: string;
    /**
     * City corresponds to IPTC field.
     *
     * @generated from protobuf field: string city = 18
     */
    city: string;
    /**
     * CreditLine corresponds to IPTC field.
     *
     * @generated from protobuf field: string credit_line = 19
     */
    creditLine: string;
    /**
     * VersionCount is the number of available versions.
     *
     * @generated from protobuf field: int32 version_count = 20
     */
    versionCount: number;
    /**
     * Instructions are any number of instructions from the provider or creator.
     *
     * @generated from protobuf field: string instructions = 21
     */
    instructions: string;
    /**
     * UsageTerms are rights usage terms.
     *
     * @generated from protobuf field: string usage_terms = 22
     */
    usageTerms: string;
    /**
     * Source is the name of a person or party who has a role in the content
     * supply chain.
     *
     * @generated from protobuf field: string source = 23
     */
    source: string;
    /**
     * Suppliers identifies the most recent supplier of the image.
     *
     * @generated from protobuf field: string suppliers = 24
     */
    suppliers: string;
    /**
     * ImageSupplierImageID is an identifier assigned by the Image Supplier.
     *
     * @generated from protobuf field: string image_supplier_image_id = 25
     */
    imageSupplierImageId: string;
    /**
     * JobID is an identifier related to the job for which the image is supplied.
     *
     * @generated from protobuf field: string job_id = 26
     */
    jobId: string;
    /**
     * File contains file information.
     *
     * @generated from protobuf field: ttab.ntb.File file = 27
     */
    file?: File;
    /**
     * Previews contains preview URLs and dimensions.
     *
     * @generated from protobuf field: repeated ttab.ntb.Preview previews = 28
     */
    previews: Preview[];
    /**
     * Permissions contains user permissions for this media.
     *
     * @generated from protobuf field: ttab.ntb.Permissions permissions = 29
     */
    permissions?: Permissions;
    /**
     * Links contains related links.
     *
     * @generated from protobuf field: map<string, string> links = 30
     */
    links: {
        [key: string]: string;
    };
    /**
     * Internal contains internal metadata.
     *
     * @generated from protobuf field: ttab.ntb.Internal internal = 31
     */
    internal?: Internal;
    /**
     * SortValues can be used for pagination in search results. Only available
     * when the MediaItem was returned as part of a search result.
     *
     * @generated from protobuf field: repeated string sort_values = 32
     */
    sortValues: string[];
}
/**
 * @generated from protobuf message ttab.ntb.ImpreciseTimestamp
 */
export interface ImpreciseTimestamp {
    /**
     * Time as an RFC3339 timestamp.
     *
     * @generated from protobuf field: string time = 1
     */
    time: string;
    /**
     * ValidTimezone is set to true if the timestamp has a valid timezone, if
     * false the timestamp will use zulu time as a substitute for the unknown
     * timezone.
     *
     * @generated from protobuf field: bool valid_timezone = 2
     */
    validTimezone: boolean;
    /**
     * Precision is a hint about the precision of the timestamp.
     *
     * @generated from protobuf field: ttab.ntb.TimestampPrecision precision = 3
     */
    precision: TimestampPrecision;
}
/**
 * @generated from protobuf message ttab.ntb.Person
 */
export interface Person {
    /**
     * PersonName is the name of the person in the image.
     *
     * @generated from protobuf field: string person_name = 1
     */
    personName: string;
    /**
     * PersonDescription is the description of the person, often their title.
     *
     * @generated from protobuf field: string person_description = 2
     */
    personDescription: string;
}
/**
 * @generated from protobuf message ttab.ntb.File
 */
export interface File {
    /**
     * Size is the size of the file in bytes.
     *
     * @generated from protobuf field: int64 size = 1
     */
    size: bigint;
    /**
     * Height is the height of the media in pixels.
     *
     * @generated from protobuf field: int32 height = 2
     */
    height: number;
    /**
     * Width is the width of the media in pixels.
     *
     * @generated from protobuf field: int32 width = 3
     */
    width: number;
    /**
     * MimeType is the mimetype of the media.
     *
     * @generated from protobuf field: string mime_type = 4
     */
    mimeType: string;
    /**
     * OriginalFilename is the original name of the file.
     *
     * @generated from protobuf field: string original_filename = 5
     */
    originalFilename: string;
}
/**
 * @generated from protobuf message ttab.ntb.Preview
 */
export interface Preview {
    /**
     * Width is the width of the preview image.
     *
     * @generated from protobuf field: int32 width = 1
     */
    width: number;
    /**
     * Height is the height of the preview image.
     *
     * @generated from protobuf field: int32 height = 2
     */
    height: number;
    /**
     * URL is the URL of the preview, can be used to preview the file.
     *
     * @generated from protobuf field: string url = 3
     */
    url: string;
    /**
     * Type is the media type of the preview.
     *
     * @generated from protobuf field: ttab.ntb.PreviewType type = 4
     */
    type: PreviewType;
}
/**
 * @generated from protobuf message ttab.ntb.Permissions
 */
export interface Permissions {
    /**
     * Edit indicates if the user can edit this media.
     *
     * @generated from protobuf field: bool edit = 1
     */
    edit: boolean;
    /**
     * Delete indicates if the user can delete this media.
     *
     * @generated from protobuf field: bool delete = 2
     */
    delete: boolean;
    /**
     * Download indicates if the user can download this media.
     *
     * @generated from protobuf field: bool download = 3
     */
    download: boolean;
}
/**
 * @generated from protobuf message ttab.ntb.Internal
 */
export interface Internal {
    /**
     * Origin contains information about the origin of the media.
     *
     * @generated from protobuf field: ttab.ntb.OriginInfo origin = 1
     */
    origin?: OriginInfo;
    /**
     * ItemID is a non-unique ID of the media provided under upload.
     *
     * @generated from protobuf field: string item_id = 2
     */
    itemId: string;
}
/**
 * @generated from protobuf message ttab.ntb.OriginInfo
 */
export interface OriginInfo {
    /**
     * Key is the key of the origin.
     *
     * @generated from protobuf field: string key = 1
     */
    key: string;
    /**
     * Name is the human readable name of the origin.
     *
     * @generated from protobuf field: string name = 2
     */
    name: string;
}
/**
 * @generated from protobuf message ttab.ntb.GetSortFieldsRequest
 */
export interface GetSortFieldsRequest {
}
/**
 * @generated from protobuf message ttab.ntb.GetSortFieldsResponse
 */
export interface GetSortFieldsResponse {
    /**
     * @generated from protobuf field: repeated ttab.ntb.SortField fields = 1
     */
    fields: SortField[];
}
/**
 * @generated from protobuf message ttab.ntb.SortField
 */
export interface SortField {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
// Enums

/**
 * @generated from protobuf enum ttab.ntb.Orientation
 */
export enum Orientation {
    /**
     * @generated from protobuf enum value: ORIENTATION_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ORIENTATION_HORIZONTAL = 1;
     */
    HORIZONTAL = 1,
    /**
     * @generated from protobuf enum value: ORIENTATION_VERTICAL = 2;
     */
    VERTICAL = 2,
    /**
     * @generated from protobuf enum value: ORIENTATION_SQUARE = 3;
     */
    SQUARE = 3
}
/**
 * @generated from protobuf enum ttab.ntb.Location
 */
export enum Location {
    /**
     * @generated from protobuf enum value: LOCATION_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LOCATION_IN_GALLERY = 1;
     */
    IN_GALLERY = 1,
    /**
     * @generated from protobuf enum value: LOCATION_NOT_IN_GALLERY = 2;
     */
    NOT_IN_GALLERY = 2,
    /**
     * @generated from protobuf enum value: LOCATION_IN_COLLECTIONS = 3;
     */
    IN_COLLECTIONS = 3,
    /**
     * @generated from protobuf enum value: LOCATION_NOT_IN_COLLECTIONS = 4;
     */
    NOT_IN_COLLECTIONS = 4,
    /**
     * @generated from protobuf enum value: LOCATION_ALL_ORGANIZATIONS = 5;
     */
    ALL_ORGANIZATIONS = 5
}
/**
 * @generated from protobuf enum ttab.ntb.Origin
 */
export enum Origin {
    /**
     * @generated from protobuf enum value: ORIGIN_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ORIGIN_UPLOAD = 1;
     */
    UPLOAD = 1,
    /**
     * @generated from protobuf enum value: ORIGIN_GUEST = 2;
     */
    GUEST = 2,
    /**
     * @generated from protobuf enum value: ORIGIN_GUESTFTP = 3;
     */
    GUESTFTP = 3,
    /**
     * @generated from protobuf enum value: ORIGIN_EMAIL = 4;
     */
    EMAIL = 4,
    /**
     * @generated from protobuf enum value: ORIGIN_IMPORT = 5;
     */
    IMPORT = 5,
    /**
     * @generated from protobuf enum value: ORIGIN_FTP = 6;
     */
    FTP = 6,
    /**
     * @generated from protobuf enum value: ORIGIN_LTR = 7;
     */
    LTR = 7,
    /**
     * @generated from protobuf enum value: ORIGIN_PS = 8;
     */
    PS = 8,
    /**
     * @generated from protobuf enum value: ORIGIN_CMS = 9;
     */
    CMS = 9
}
/**
 * @generated from protobuf enum ttab.ntb.FileType
 */
export enum FileType {
    /**
     * @generated from protobuf enum value: FILE_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: FILE_TYPE_IMAGE = 1;
     */
    IMAGE = 1,
    /**
     * @generated from protobuf enum value: FILE_TYPE_VIDEO = 2;
     */
    VIDEO = 2,
    /**
     * @generated from protobuf enum value: FILE_TYPE_PDF = 3;
     */
    PDF = 3,
    /**
     * @generated from protobuf enum value: FILE_TYPE_VECTOR = 4;
     */
    VECTOR = 4,
    /**
     * @generated from protobuf enum value: FILE_TYPE_PHOTOSHOP = 5;
     */
    PHOTOSHOP = 5
}
/**
 * @generated from protobuf enum ttab.ntb.TimestampPrecision
 */
export enum TimestampPrecision {
    /**
     * @generated from protobuf enum value: TS_PRECISION_UNKNOWN = 0;
     */
    TS_PRECISION_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: TS_PRECISION_FULL = 1;
     */
    TS_PRECISION_FULL = 1,
    /**
     * @generated from protobuf enum value: TS_PRECISION_MINUTE = 2;
     */
    TS_PRECISION_MINUTE = 2,
    /**
     * @generated from protobuf enum value: TS_PRECISION_HOUR = 3;
     */
    TS_PRECISION_HOUR = 3,
    /**
     * @generated from protobuf enum value: TS_PRECISION_DAY = 4;
     */
    TS_PRECISION_DAY = 4,
    /**
     * @generated from protobuf enum value: TS_PRECISION_MONTH = 5;
     */
    TS_PRECISION_MONTH = 5,
    /**
     * @generated from protobuf enum value: TS_PRECISION_YEAR = 6;
     */
    TS_PRECISION_YEAR = 6,
    /**
     * @generated from protobuf enum value: TS_PRECISION_DECADE = 7;
     */
    TS_PRECISION_DECADE = 7,
    /**
     * @generated from protobuf enum value: TS_PRECISION_CENTURY = 8;
     */
    TS_PRECISION_CENTURY = 8
}
/**
 * @generated from protobuf enum ttab.ntb.PreviewType
 */
export enum PreviewType {
    /**
     * @generated from protobuf enum value: PREVIEW_UNKNOWN = 0;
     */
    PREVIEW_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: PREVIEW_IMAGE = 1;
     */
    PREVIEW_IMAGE = 1,
    /**
     * @generated from protobuf enum value: PREVIEW_VIDEO = 2;
     */
    PREVIEW_VIDEO = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAssignmentRequest$Type extends MessageType<GetAssignmentRequest> {
    constructor() {
        super("ttab.ntb.GetAssignmentRequest", [
            { no: 1, name: "commission_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetAssignmentRequest>): GetAssignmentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.commissionCode = "";
        if (value !== undefined)
            reflectionMergePartial<GetAssignmentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAssignmentRequest): GetAssignmentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string commission_code */ 1:
                    message.commissionCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAssignmentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string commission_code = 1; */
        if (message.commissionCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.commissionCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.GetAssignmentRequest
 */
export const GetAssignmentRequest = new GetAssignmentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAssignmentResponse$Type extends MessageType<GetAssignmentResponse> {
    constructor() {
        super("ttab.ntb.GetAssignmentResponse", [
            { no: 1, name: "planning_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "assignment_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetAssignmentResponse>): GetAssignmentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.planningUuid = "";
        message.assignmentUuid = "";
        if (value !== undefined)
            reflectionMergePartial<GetAssignmentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAssignmentResponse): GetAssignmentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string planning_uuid */ 1:
                    message.planningUuid = reader.string();
                    break;
                case /* string assignment_uuid */ 2:
                    message.assignmentUuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAssignmentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string planning_uuid = 1; */
        if (message.planningUuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.planningUuid);
        /* string assignment_uuid = 2; */
        if (message.assignmentUuid !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.assignmentUuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.GetAssignmentResponse
 */
export const GetAssignmentResponse = new GetAssignmentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetItemRequest$Type extends MessageType<GetItemRequest> {
    constructor() {
        super("ttab.ntb.GetItemRequest", [
            { no: 1, name: "archive", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetItemRequest>): GetItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.archive = "";
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<GetItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetItemRequest): GetItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string archive */ 1:
                    message.archive = reader.string();
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string archive = 1; */
        if (message.archive !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.archive);
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.GetItemRequest
 */
export const GetItemRequest = new GetItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetItemResponse$Type extends MessageType<GetItemResponse> {
    constructor() {
        super("ttab.ntb.GetItemResponse", [
            { no: 1, name: "item", kind: "message", T: () => MediaItem }
        ]);
    }
    create(value?: PartialMessage<GetItemResponse>): GetItemResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetItemResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetItemResponse): GetItemResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ttab.ntb.MediaItem item */ 1:
                    message.item = MediaItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetItemResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ttab.ntb.MediaItem item = 1; */
        if (message.item)
            MediaItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.GetItemResponse
 */
export const GetItemResponse = new GetItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchRequest$Type extends MessageType<SearchRequest> {
    constructor() {
        super("ttab.ntb.SearchRequest", [
            { no: 1, name: "archive", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "sort", kind: "message", T: () => Sort },
            { no: 5, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "city", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "country", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "creator", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "keywords", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "collections", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "albums", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "categories", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "locations", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "orientation", kind: "enum", T: () => ["ttab.ntb.Orientation", Orientation, "ORIENTATION_"] },
            { no: 18, name: "search_after", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "origins", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["ttab.ntb.Origin", Origin, "ORIGIN_"] },
            { no: 20, name: "file_type", kind: "enum", T: () => ["ttab.ntb.FileType", FileType, "FILE_TYPE_"] },
            { no: 21, name: "created_min", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "created_max", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "outside_subscription", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SearchRequest>): SearchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.archive = "";
        message.limit = 0;
        message.offset = 0;
        message.query = "";
        message.itemId = "";
        message.city = "";
        message.country = "";
        message.creator = "";
        message.ids = [];
        message.keywords = [];
        message.collections = [];
        message.albums = [];
        message.categories = [];
        message.locations = "";
        message.jobId = "";
        message.orientation = 0;
        message.searchAfter = [];
        message.origins = [];
        message.fileType = 0;
        message.createdMin = "";
        message.createdMax = "";
        message.outsideSubscription = false;
        if (value !== undefined)
            reflectionMergePartial<SearchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchRequest): SearchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string archive */ 1:
                    message.archive = reader.string();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* int32 offset */ 3:
                    message.offset = reader.int32();
                    break;
                case /* ttab.ntb.Sort sort */ 4:
                    message.sort = Sort.internalBinaryRead(reader, reader.uint32(), options, message.sort);
                    break;
                case /* string query */ 5:
                    message.query = reader.string();
                    break;
                case /* string item_id */ 6:
                    message.itemId = reader.string();
                    break;
                case /* string city */ 7:
                    message.city = reader.string();
                    break;
                case /* string country */ 8:
                    message.country = reader.string();
                    break;
                case /* string creator */ 9:
                    message.creator = reader.string();
                    break;
                case /* repeated string ids */ 10:
                    message.ids.push(reader.string());
                    break;
                case /* repeated string keywords */ 11:
                    message.keywords.push(reader.string());
                    break;
                case /* repeated int32 collections */ 12:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.collections.push(reader.int32());
                    else
                        message.collections.push(reader.int32());
                    break;
                case /* repeated int32 albums */ 13:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.albums.push(reader.int32());
                    else
                        message.albums.push(reader.int32());
                    break;
                case /* repeated string categories */ 14:
                    message.categories.push(reader.string());
                    break;
                case /* string locations */ 15:
                    message.locations = reader.string();
                    break;
                case /* string job_id */ 16:
                    message.jobId = reader.string();
                    break;
                case /* ttab.ntb.Orientation orientation */ 17:
                    message.orientation = reader.int32();
                    break;
                case /* repeated string search_after */ 18:
                    message.searchAfter.push(reader.string());
                    break;
                case /* repeated ttab.ntb.Origin origins */ 19:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.origins.push(reader.int32());
                    else
                        message.origins.push(reader.int32());
                    break;
                case /* ttab.ntb.FileType file_type */ 20:
                    message.fileType = reader.int32();
                    break;
                case /* string created_min */ 21:
                    message.createdMin = reader.string();
                    break;
                case /* string created_max */ 22:
                    message.createdMax = reader.string();
                    break;
                case /* bool outside_subscription */ 23:
                    message.outsideSubscription = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string archive = 1; */
        if (message.archive !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.archive);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* int32 offset = 3; */
        if (message.offset !== 0)
            writer.tag(3, WireType.Varint).int32(message.offset);
        /* ttab.ntb.Sort sort = 4; */
        if (message.sort)
            Sort.internalBinaryWrite(message.sort, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string query = 5; */
        if (message.query !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.query);
        /* string item_id = 6; */
        if (message.itemId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.itemId);
        /* string city = 7; */
        if (message.city !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.city);
        /* string country = 8; */
        if (message.country !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.country);
        /* string creator = 9; */
        if (message.creator !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.creator);
        /* repeated string ids = 10; */
        for (let i = 0; i < message.ids.length; i++)
            writer.tag(10, WireType.LengthDelimited).string(message.ids[i]);
        /* repeated string keywords = 11; */
        for (let i = 0; i < message.keywords.length; i++)
            writer.tag(11, WireType.LengthDelimited).string(message.keywords[i]);
        /* repeated int32 collections = 12; */
        if (message.collections.length) {
            writer.tag(12, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.collections.length; i++)
                writer.int32(message.collections[i]);
            writer.join();
        }
        /* repeated int32 albums = 13; */
        if (message.albums.length) {
            writer.tag(13, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.albums.length; i++)
                writer.int32(message.albums[i]);
            writer.join();
        }
        /* repeated string categories = 14; */
        for (let i = 0; i < message.categories.length; i++)
            writer.tag(14, WireType.LengthDelimited).string(message.categories[i]);
        /* string locations = 15; */
        if (message.locations !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.locations);
        /* string job_id = 16; */
        if (message.jobId !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.jobId);
        /* ttab.ntb.Orientation orientation = 17; */
        if (message.orientation !== 0)
            writer.tag(17, WireType.Varint).int32(message.orientation);
        /* repeated string search_after = 18; */
        for (let i = 0; i < message.searchAfter.length; i++)
            writer.tag(18, WireType.LengthDelimited).string(message.searchAfter[i]);
        /* repeated ttab.ntb.Origin origins = 19; */
        if (message.origins.length) {
            writer.tag(19, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.origins.length; i++)
                writer.int32(message.origins[i]);
            writer.join();
        }
        /* ttab.ntb.FileType file_type = 20; */
        if (message.fileType !== 0)
            writer.tag(20, WireType.Varint).int32(message.fileType);
        /* string created_min = 21; */
        if (message.createdMin !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.createdMin);
        /* string created_max = 22; */
        if (message.createdMax !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.createdMax);
        /* bool outside_subscription = 23; */
        if (message.outsideSubscription !== false)
            writer.tag(23, WireType.Varint).bool(message.outsideSubscription);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.SearchRequest
 */
export const SearchRequest = new SearchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Sort$Type extends MessageType<Sort> {
    constructor() {
        super("ttab.ntb.Sort", [
            { no: 1, name: "field", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "descending", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Sort>): Sort {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.field = "";
        message.descending = false;
        if (value !== undefined)
            reflectionMergePartial<Sort>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Sort): Sort {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string field */ 1:
                    message.field = reader.string();
                    break;
                case /* bool descending */ 2:
                    message.descending = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Sort, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string field = 1; */
        if (message.field !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.field);
        /* bool descending = 2; */
        if (message.descending !== false)
            writer.tag(2, WireType.Varint).bool(message.descending);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.Sort
 */
export const Sort = new Sort$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchResponse$Type extends MessageType<SearchResponse> {
    constructor() {
        super("ttab.ntb.SearchResponse", [
            { no: 1, name: "page", kind: "message", T: () => Page },
            { no: 3, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MediaItem }
        ]);
    }
    create(value?: PartialMessage<SearchResponse>): SearchResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<SearchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchResponse): SearchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ttab.ntb.Page page */ 1:
                    message.page = Page.internalBinaryRead(reader, reader.uint32(), options, message.page);
                    break;
                case /* repeated ttab.ntb.MediaItem data */ 3:
                    message.data.push(MediaItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ttab.ntb.Page page = 1; */
        if (message.page)
            Page.internalBinaryWrite(message.page, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated ttab.ntb.MediaItem data = 3; */
        for (let i = 0; i < message.data.length; i++)
            MediaItem.internalBinaryWrite(message.data[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.SearchResponse
 */
export const SearchResponse = new SearchResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Page$Type extends MessageType<Page> {
    constructor() {
        super("ttab.ntb.Page", [
            { no: 1, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "search_after", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Page>): Page {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offset = 0;
        message.limit = 0;
        message.count = 0;
        message.total = 0;
        message.searchAfter = [];
        if (value !== undefined)
            reflectionMergePartial<Page>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Page): Page {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 offset */ 1:
                    message.offset = reader.int32();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* int32 count */ 3:
                    message.count = reader.int32();
                    break;
                case /* int32 total */ 4:
                    message.total = reader.int32();
                    break;
                case /* repeated string search_after */ 5:
                    message.searchAfter.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Page, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 offset = 1; */
        if (message.offset !== 0)
            writer.tag(1, WireType.Varint).int32(message.offset);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* int32 count = 3; */
        if (message.count !== 0)
            writer.tag(3, WireType.Varint).int32(message.count);
        /* int32 total = 4; */
        if (message.total !== 0)
            writer.tag(4, WireType.Varint).int32(message.total);
        /* repeated string search_after = 5; */
        for (let i = 0; i < message.searchAfter.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.searchAfter[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.Page
 */
export const Page = new Page$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MediaItem$Type extends MessageType<MediaItem> {
    constructor() {
        super("ttab.ntb.MediaItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "archive", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "restrictions", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "headline", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "alt_text_accessibility", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "creator", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "keywords", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "persons_shown", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Person },
            { no: 13, name: "image_rating", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "date_archived", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "date_created", kind: "message", T: () => ImpreciseTimestamp },
            { no: 17, name: "country", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "city", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "credit_line", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "version_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "instructions", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "usage_terms", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "suppliers", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "image_supplier_image_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 26, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 27, name: "file", kind: "message", T: () => File },
            { no: 28, name: "previews", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Preview },
            { no: 29, name: "permissions", kind: "message", T: () => Permissions },
            { no: 30, name: "links", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 31, name: "internal", kind: "message", T: () => Internal },
            { no: 32, name: "sort_values", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MediaItem>): MediaItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.type = "";
        message.archive = "";
        message.userId = "";
        message.restrictions = false;
        message.headline = "";
        message.description = "";
        message.altTextAccessibility = "";
        message.creator = "";
        message.keywords = [];
        message.category = "";
        message.personsShown = [];
        message.title = "";
        message.dateArchived = "";
        message.country = "";
        message.city = "";
        message.creditLine = "";
        message.versionCount = 0;
        message.instructions = "";
        message.usageTerms = "";
        message.source = "";
        message.suppliers = "";
        message.imageSupplierImageId = "";
        message.jobId = "";
        message.previews = [];
        message.links = {};
        message.sortValues = [];
        if (value !== undefined)
            reflectionMergePartial<MediaItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MediaItem): MediaItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string type */ 2:
                    message.type = reader.string();
                    break;
                case /* string archive */ 3:
                    message.archive = reader.string();
                    break;
                case /* string user_id */ 4:
                    message.userId = reader.string();
                    break;
                case /* bool restrictions */ 5:
                    message.restrictions = reader.bool();
                    break;
                case /* string headline */ 6:
                    message.headline = reader.string();
                    break;
                case /* string description */ 7:
                    message.description = reader.string();
                    break;
                case /* string alt_text_accessibility */ 8:
                    message.altTextAccessibility = reader.string();
                    break;
                case /* string creator */ 9:
                    message.creator = reader.string();
                    break;
                case /* repeated string keywords */ 10:
                    message.keywords.push(reader.string());
                    break;
                case /* string category */ 11:
                    message.category = reader.string();
                    break;
                case /* repeated ttab.ntb.Person persons_shown */ 12:
                    message.personsShown.push(Person.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional int32 image_rating */ 13:
                    message.imageRating = reader.int32();
                    break;
                case /* string title */ 14:
                    message.title = reader.string();
                    break;
                case /* string date_archived */ 15:
                    message.dateArchived = reader.string();
                    break;
                case /* ttab.ntb.ImpreciseTimestamp date_created */ 16:
                    message.dateCreated = ImpreciseTimestamp.internalBinaryRead(reader, reader.uint32(), options, message.dateCreated);
                    break;
                case /* string country */ 17:
                    message.country = reader.string();
                    break;
                case /* string city */ 18:
                    message.city = reader.string();
                    break;
                case /* string credit_line */ 19:
                    message.creditLine = reader.string();
                    break;
                case /* int32 version_count */ 20:
                    message.versionCount = reader.int32();
                    break;
                case /* string instructions */ 21:
                    message.instructions = reader.string();
                    break;
                case /* string usage_terms */ 22:
                    message.usageTerms = reader.string();
                    break;
                case /* string source */ 23:
                    message.source = reader.string();
                    break;
                case /* string suppliers */ 24:
                    message.suppliers = reader.string();
                    break;
                case /* string image_supplier_image_id */ 25:
                    message.imageSupplierImageId = reader.string();
                    break;
                case /* string job_id */ 26:
                    message.jobId = reader.string();
                    break;
                case /* ttab.ntb.File file */ 27:
                    message.file = File.internalBinaryRead(reader, reader.uint32(), options, message.file);
                    break;
                case /* repeated ttab.ntb.Preview previews */ 28:
                    message.previews.push(Preview.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* ttab.ntb.Permissions permissions */ 29:
                    message.permissions = Permissions.internalBinaryRead(reader, reader.uint32(), options, message.permissions);
                    break;
                case /* map<string, string> links */ 30:
                    this.binaryReadMap30(message.links, reader, options);
                    break;
                case /* ttab.ntb.Internal internal */ 31:
                    message.internal = Internal.internalBinaryRead(reader, reader.uint32(), options, message.internal);
                    break;
                case /* repeated string sort_values */ 32:
                    message.sortValues.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap30(map: MediaItem["links"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof MediaItem["links"] | undefined, val: MediaItem["links"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for ttab.ntb.MediaItem.links");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: MediaItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string type = 2; */
        if (message.type !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.type);
        /* string archive = 3; */
        if (message.archive !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.archive);
        /* string user_id = 4; */
        if (message.userId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.userId);
        /* bool restrictions = 5; */
        if (message.restrictions !== false)
            writer.tag(5, WireType.Varint).bool(message.restrictions);
        /* string headline = 6; */
        if (message.headline !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.headline);
        /* string description = 7; */
        if (message.description !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        /* string alt_text_accessibility = 8; */
        if (message.altTextAccessibility !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.altTextAccessibility);
        /* string creator = 9; */
        if (message.creator !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.creator);
        /* repeated string keywords = 10; */
        for (let i = 0; i < message.keywords.length; i++)
            writer.tag(10, WireType.LengthDelimited).string(message.keywords[i]);
        /* string category = 11; */
        if (message.category !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.category);
        /* repeated ttab.ntb.Person persons_shown = 12; */
        for (let i = 0; i < message.personsShown.length; i++)
            Person.internalBinaryWrite(message.personsShown[i], writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* optional int32 image_rating = 13; */
        if (message.imageRating !== undefined)
            writer.tag(13, WireType.Varint).int32(message.imageRating);
        /* string title = 14; */
        if (message.title !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.title);
        /* string date_archived = 15; */
        if (message.dateArchived !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.dateArchived);
        /* ttab.ntb.ImpreciseTimestamp date_created = 16; */
        if (message.dateCreated)
            ImpreciseTimestamp.internalBinaryWrite(message.dateCreated, writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        /* string country = 17; */
        if (message.country !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.country);
        /* string city = 18; */
        if (message.city !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.city);
        /* string credit_line = 19; */
        if (message.creditLine !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.creditLine);
        /* int32 version_count = 20; */
        if (message.versionCount !== 0)
            writer.tag(20, WireType.Varint).int32(message.versionCount);
        /* string instructions = 21; */
        if (message.instructions !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.instructions);
        /* string usage_terms = 22; */
        if (message.usageTerms !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.usageTerms);
        /* string source = 23; */
        if (message.source !== "")
            writer.tag(23, WireType.LengthDelimited).string(message.source);
        /* string suppliers = 24; */
        if (message.suppliers !== "")
            writer.tag(24, WireType.LengthDelimited).string(message.suppliers);
        /* string image_supplier_image_id = 25; */
        if (message.imageSupplierImageId !== "")
            writer.tag(25, WireType.LengthDelimited).string(message.imageSupplierImageId);
        /* string job_id = 26; */
        if (message.jobId !== "")
            writer.tag(26, WireType.LengthDelimited).string(message.jobId);
        /* ttab.ntb.File file = 27; */
        if (message.file)
            File.internalBinaryWrite(message.file, writer.tag(27, WireType.LengthDelimited).fork(), options).join();
        /* repeated ttab.ntb.Preview previews = 28; */
        for (let i = 0; i < message.previews.length; i++)
            Preview.internalBinaryWrite(message.previews[i], writer.tag(28, WireType.LengthDelimited).fork(), options).join();
        /* ttab.ntb.Permissions permissions = 29; */
        if (message.permissions)
            Permissions.internalBinaryWrite(message.permissions, writer.tag(29, WireType.LengthDelimited).fork(), options).join();
        /* map<string, string> links = 30; */
        for (let k of globalThis.Object.keys(message.links))
            writer.tag(30, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.links[k]).join();
        /* ttab.ntb.Internal internal = 31; */
        if (message.internal)
            Internal.internalBinaryWrite(message.internal, writer.tag(31, WireType.LengthDelimited).fork(), options).join();
        /* repeated string sort_values = 32; */
        for (let i = 0; i < message.sortValues.length; i++)
            writer.tag(32, WireType.LengthDelimited).string(message.sortValues[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.MediaItem
 */
export const MediaItem = new MediaItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImpreciseTimestamp$Type extends MessageType<ImpreciseTimestamp> {
    constructor() {
        super("ttab.ntb.ImpreciseTimestamp", [
            { no: 1, name: "time", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "valid_timezone", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "precision", kind: "enum", T: () => ["ttab.ntb.TimestampPrecision", TimestampPrecision] }
        ]);
    }
    create(value?: PartialMessage<ImpreciseTimestamp>): ImpreciseTimestamp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.time = "";
        message.validTimezone = false;
        message.precision = 0;
        if (value !== undefined)
            reflectionMergePartial<ImpreciseTimestamp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImpreciseTimestamp): ImpreciseTimestamp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string time */ 1:
                    message.time = reader.string();
                    break;
                case /* bool valid_timezone */ 2:
                    message.validTimezone = reader.bool();
                    break;
                case /* ttab.ntb.TimestampPrecision precision */ 3:
                    message.precision = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ImpreciseTimestamp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string time = 1; */
        if (message.time !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.time);
        /* bool valid_timezone = 2; */
        if (message.validTimezone !== false)
            writer.tag(2, WireType.Varint).bool(message.validTimezone);
        /* ttab.ntb.TimestampPrecision precision = 3; */
        if (message.precision !== 0)
            writer.tag(3, WireType.Varint).int32(message.precision);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.ImpreciseTimestamp
 */
export const ImpreciseTimestamp = new ImpreciseTimestamp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Person$Type extends MessageType<Person> {
    constructor() {
        super("ttab.ntb.Person", [
            { no: 1, name: "person_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "person_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Person>): Person {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.personName = "";
        message.personDescription = "";
        if (value !== undefined)
            reflectionMergePartial<Person>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Person): Person {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string person_name */ 1:
                    message.personName = reader.string();
                    break;
                case /* string person_description */ 2:
                    message.personDescription = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Person, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string person_name = 1; */
        if (message.personName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.personName);
        /* string person_description = 2; */
        if (message.personDescription !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.personDescription);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.Person
 */
export const Person = new Person$Type();
// @generated message type with reflection information, may provide speed optimized methods
class File$Type extends MessageType<File> {
    constructor() {
        super("ttab.ntb.File", [
            { no: 1, name: "size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "original_filename", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<File>): File {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.size = 0n;
        message.height = 0;
        message.width = 0;
        message.mimeType = "";
        message.originalFilename = "";
        if (value !== undefined)
            reflectionMergePartial<File>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: File): File {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 size */ 1:
                    message.size = reader.int64().toBigInt();
                    break;
                case /* int32 height */ 2:
                    message.height = reader.int32();
                    break;
                case /* int32 width */ 3:
                    message.width = reader.int32();
                    break;
                case /* string mime_type */ 4:
                    message.mimeType = reader.string();
                    break;
                case /* string original_filename */ 5:
                    message.originalFilename = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: File, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 size = 1; */
        if (message.size !== 0n)
            writer.tag(1, WireType.Varint).int64(message.size);
        /* int32 height = 2; */
        if (message.height !== 0)
            writer.tag(2, WireType.Varint).int32(message.height);
        /* int32 width = 3; */
        if (message.width !== 0)
            writer.tag(3, WireType.Varint).int32(message.width);
        /* string mime_type = 4; */
        if (message.mimeType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.mimeType);
        /* string original_filename = 5; */
        if (message.originalFilename !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.originalFilename);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.File
 */
export const File = new File$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Preview$Type extends MessageType<Preview> {
    constructor() {
        super("ttab.ntb.Preview", [
            { no: 1, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "enum", T: () => ["ttab.ntb.PreviewType", PreviewType] }
        ]);
    }
    create(value?: PartialMessage<Preview>): Preview {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.width = 0;
        message.height = 0;
        message.url = "";
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<Preview>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Preview): Preview {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 width */ 1:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 2:
                    message.height = reader.int32();
                    break;
                case /* string url */ 3:
                    message.url = reader.string();
                    break;
                case /* ttab.ntb.PreviewType type */ 4:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Preview, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 width = 1; */
        if (message.width !== 0)
            writer.tag(1, WireType.Varint).int32(message.width);
        /* int32 height = 2; */
        if (message.height !== 0)
            writer.tag(2, WireType.Varint).int32(message.height);
        /* string url = 3; */
        if (message.url !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.url);
        /* ttab.ntb.PreviewType type = 4; */
        if (message.type !== 0)
            writer.tag(4, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.Preview
 */
export const Preview = new Preview$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Permissions$Type extends MessageType<Permissions> {
    constructor() {
        super("ttab.ntb.Permissions", [
            { no: 1, name: "edit", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "delete", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "download", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Permissions>): Permissions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.edit = false;
        message.delete = false;
        message.download = false;
        if (value !== undefined)
            reflectionMergePartial<Permissions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Permissions): Permissions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool edit */ 1:
                    message.edit = reader.bool();
                    break;
                case /* bool delete */ 2:
                    message.delete = reader.bool();
                    break;
                case /* bool download */ 3:
                    message.download = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Permissions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool edit = 1; */
        if (message.edit !== false)
            writer.tag(1, WireType.Varint).bool(message.edit);
        /* bool delete = 2; */
        if (message.delete !== false)
            writer.tag(2, WireType.Varint).bool(message.delete);
        /* bool download = 3; */
        if (message.download !== false)
            writer.tag(3, WireType.Varint).bool(message.download);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.Permissions
 */
export const Permissions = new Permissions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Internal$Type extends MessageType<Internal> {
    constructor() {
        super("ttab.ntb.Internal", [
            { no: 1, name: "origin", kind: "message", T: () => OriginInfo },
            { no: 2, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Internal>): Internal {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.itemId = "";
        if (value !== undefined)
            reflectionMergePartial<Internal>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Internal): Internal {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ttab.ntb.OriginInfo origin */ 1:
                    message.origin = OriginInfo.internalBinaryRead(reader, reader.uint32(), options, message.origin);
                    break;
                case /* string item_id */ 2:
                    message.itemId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Internal, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ttab.ntb.OriginInfo origin = 1; */
        if (message.origin)
            OriginInfo.internalBinaryWrite(message.origin, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string item_id = 2; */
        if (message.itemId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.itemId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.Internal
 */
export const Internal = new Internal$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OriginInfo$Type extends MessageType<OriginInfo> {
    constructor() {
        super("ttab.ntb.OriginInfo", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<OriginInfo>): OriginInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.key = "";
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<OriginInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OriginInfo): OriginInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string key */ 1:
                    message.key = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OriginInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string key = 1; */
        if (message.key !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.key);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.OriginInfo
 */
export const OriginInfo = new OriginInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSortFieldsRequest$Type extends MessageType<GetSortFieldsRequest> {
    constructor() {
        super("ttab.ntb.GetSortFieldsRequest", []);
    }
    create(value?: PartialMessage<GetSortFieldsRequest>): GetSortFieldsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetSortFieldsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSortFieldsRequest): GetSortFieldsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSortFieldsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.GetSortFieldsRequest
 */
export const GetSortFieldsRequest = new GetSortFieldsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSortFieldsResponse$Type extends MessageType<GetSortFieldsResponse> {
    constructor() {
        super("ttab.ntb.GetSortFieldsResponse", [
            { no: 1, name: "fields", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SortField }
        ]);
    }
    create(value?: PartialMessage<GetSortFieldsResponse>): GetSortFieldsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fields = [];
        if (value !== undefined)
            reflectionMergePartial<GetSortFieldsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSortFieldsResponse): GetSortFieldsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ttab.ntb.SortField fields */ 1:
                    message.fields.push(SortField.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSortFieldsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ttab.ntb.SortField fields = 1; */
        for (let i = 0; i < message.fields.length; i++)
            SortField.internalBinaryWrite(message.fields[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.GetSortFieldsResponse
 */
export const GetSortFieldsResponse = new GetSortFieldsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SortField$Type extends MessageType<SortField> {
    constructor() {
        super("ttab.ntb.SortField", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SortField>): SortField {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<SortField>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SortField): SortField {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SortField, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.ntb.SortField
 */
export const SortField = new SortField$Type();
/**
 * @generated ServiceType for protobuf service ttab.ntb.Metadata
 */
export const Metadata = new ServiceType("ttab.ntb.Metadata", [
    { name: "GetAssignment", options: {}, I: GetAssignmentRequest, O: GetAssignmentResponse }
]);
/**
 * @generated ServiceType for protobuf service ttab.ntb.Media
 */
export const Media = new ServiceType("ttab.ntb.Media", [
    { name: "Search", options: {}, I: SearchRequest, O: SearchResponse },
    { name: "GetItem", options: {}, I: GetItemRequest, O: GetItemResponse },
    { name: "GetSortFields", options: {}, I: GetSortFieldsRequest, O: GetSortFieldsResponse }
]);
