/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "ntb/service.proto" (package "ttab.ntb", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Media } from "./service";
import type { GetSortFieldsResponse } from "./service";
import type { GetSortFieldsRequest } from "./service";
import type { GetItemResponse } from "./service";
import type { GetItemRequest } from "./service";
import type { SearchResponse } from "./service";
import type { SearchRequest } from "./service";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Metadata } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetAssignmentResponse } from "./service";
import type { GetAssignmentRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Metadata service for retrieving assignment metadata.
 *
 * @generated from protobuf service ttab.ntb.Metadata
 */
export interface IMetadataClient {
    /**
     * GetAssignment returns metadata for a specific assignment.
     *
     * @generated from protobuf rpc: GetAssignment
     */
    getAssignment(input: GetAssignmentRequest, options?: RpcOptions): UnaryCall<GetAssignmentRequest, GetAssignmentResponse>;
}
/**
 * Metadata service for retrieving assignment metadata.
 *
 * @generated from protobuf service ttab.ntb.Metadata
 */
export class MetadataClient implements IMetadataClient, ServiceInfo {
    typeName = Metadata.typeName;
    methods = Metadata.methods;
    options = Metadata.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetAssignment returns metadata for a specific assignment.
     *
     * @generated from protobuf rpc: GetAssignment
     */
    getAssignment(input: GetAssignmentRequest, options?: RpcOptions): UnaryCall<GetAssignmentRequest, GetAssignmentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAssignmentRequest, GetAssignmentResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Media service for interacting with the NTB media manager archive. Experimental.
 *
 * @generated from protobuf service ttab.ntb.Media
 */
export interface IMediaClient {
    /**
     * Search in a media archive.
     *
     * @generated from protobuf rpc: Search
     */
    search(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse>;
    /**
     * GetItem fetches a single media item.
     *
     * @generated from protobuf rpc: GetItem
     */
    getItem(input: GetItemRequest, options?: RpcOptions): UnaryCall<GetItemRequest, GetItemResponse>;
    /**
     * GetSortFields returns the available sort fields.
     *
     * @generated from protobuf rpc: GetSortFields
     */
    getSortFields(input: GetSortFieldsRequest, options?: RpcOptions): UnaryCall<GetSortFieldsRequest, GetSortFieldsResponse>;
}
/**
 * Media service for interacting with the NTB media manager archive. Experimental.
 *
 * @generated from protobuf service ttab.ntb.Media
 */
export class MediaClient implements IMediaClient, ServiceInfo {
    typeName = Media.typeName;
    methods = Media.methods;
    options = Media.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Search in a media archive.
     *
     * @generated from protobuf rpc: Search
     */
    search(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchRequest, SearchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetItem fetches a single media item.
     *
     * @generated from protobuf rpc: GetItem
     */
    getItem(input: GetItemRequest, options?: RpcOptions): UnaryCall<GetItemRequest, GetItemResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetItemRequest, GetItemResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetSortFields returns the available sort fields.
     *
     * @generated from protobuf rpc: GetSortFields
     */
    getSortFields(input: GetSortFieldsRequest, options?: RpcOptions): UnaryCall<GetSortFieldsRequest, GetSortFieldsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSortFieldsRequest, GetSortFieldsResponse>("unary", this._transport, method, opt, input);
    }
}
