/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "ntb/service.proto" (package "ttab.ntb", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Nynorsk } from "./service";
import type { GetPreferenceTemplatesResponse } from "./service";
import type { GetPreferenceTemplatesRequest } from "./service";
import type { GetDocumentFormatsResponse } from "./service";
import type { GetDocumentFormatsRequest } from "./service";
import type { GetLanguagePrefsResponse } from "./service";
import type { GetLanguagePrefsRequest } from "./service";
import type { TranslateResponse } from "./service";
import type { TranslateRequest } from "./service";
import { Media } from "./service";
import type { GetSortFieldsResponse } from "./service";
import type { GetSortFieldsRequest } from "./service";
import type { GetItemResponse } from "./service";
import type { GetItemRequest } from "./service";
import type { SearchResponse } from "./service";
import type { SearchRequest } from "./service";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Metadata } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetAssignmentResponse } from "./service";
import type { GetAssignmentRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Metadata service for retrieving assignment metadata.
 *
 * @generated from protobuf service ttab.ntb.Metadata
 */
export interface IMetadataClient {
    /**
     * GetAssignment returns metadata for a specific assignment.
     *
     * @generated from protobuf rpc: GetAssignment
     */
    getAssignment(input: GetAssignmentRequest, options?: RpcOptions): UnaryCall<GetAssignmentRequest, GetAssignmentResponse>;
}
/**
 * Metadata service for retrieving assignment metadata.
 *
 * @generated from protobuf service ttab.ntb.Metadata
 */
export class MetadataClient implements IMetadataClient, ServiceInfo {
    typeName = Metadata.typeName;
    methods = Metadata.methods;
    options = Metadata.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetAssignment returns metadata for a specific assignment.
     *
     * @generated from protobuf rpc: GetAssignment
     */
    getAssignment(input: GetAssignmentRequest, options?: RpcOptions): UnaryCall<GetAssignmentRequest, GetAssignmentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAssignmentRequest, GetAssignmentResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Media service for interacting with the NTB media manager archive. Experimental.
 *
 * @generated from protobuf service ttab.ntb.Media
 */
export interface IMediaClient {
    /**
     * Search in a media archive.
     *
     * @generated from protobuf rpc: Search
     */
    search(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse>;
    /**
     * GetItem fetches a single media item.
     *
     * @generated from protobuf rpc: GetItem
     */
    getItem(input: GetItemRequest, options?: RpcOptions): UnaryCall<GetItemRequest, GetItemResponse>;
    /**
     * GetSortFields returns the available sort fields.
     *
     * @generated from protobuf rpc: GetSortFields
     */
    getSortFields(input: GetSortFieldsRequest, options?: RpcOptions): UnaryCall<GetSortFieldsRequest, GetSortFieldsResponse>;
}
/**
 * Media service for interacting with the NTB media manager archive. Experimental.
 *
 * @generated from protobuf service ttab.ntb.Media
 */
export class MediaClient implements IMediaClient, ServiceInfo {
    typeName = Media.typeName;
    methods = Media.methods;
    options = Media.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Search in a media archive.
     *
     * @generated from protobuf rpc: Search
     */
    search(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchRequest, SearchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetItem fetches a single media item.
     *
     * @generated from protobuf rpc: GetItem
     */
    getItem(input: GetItemRequest, options?: RpcOptions): UnaryCall<GetItemRequest, GetItemResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetItemRequest, GetItemResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetSortFields returns the available sort fields.
     *
     * @generated from protobuf rpc: GetSortFields
     */
    getSortFields(input: GetSortFieldsRequest, options?: RpcOptions): UnaryCall<GetSortFieldsRequest, GetSortFieldsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSortFieldsRequest, GetSortFieldsResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Nynorsk service for translating documents using Nynorskroboten.
 *
 * @generated from protobuf service ttab.ntb.Nynorsk
 */
export interface INynorskClient {
    /**
     * Translate translates a document between Scandinavian languages.
     *
     * @generated from protobuf rpc: Translate
     */
    translate(input: TranslateRequest, options?: RpcOptions): UnaryCall<TranslateRequest, TranslateResponse>;
    /**
     * GetLanguagePrefs returns the available optional language forms.
     *
     * @generated from protobuf rpc: GetLanguagePrefs
     */
    getLanguagePrefs(input: GetLanguagePrefsRequest, options?: RpcOptions): UnaryCall<GetLanguagePrefsRequest, GetLanguagePrefsResponse>;
    /**
     * GetDocumentFormats returns the supported document formats.
     *
     * @generated from protobuf rpc: GetDocumentFormats
     */
    getDocumentFormats(input: GetDocumentFormatsRequest, options?: RpcOptions): UnaryCall<GetDocumentFormatsRequest, GetDocumentFormatsResponse>;
    /**
     * GetPreferenceTemplates returns the available preference templates and the
     * language forms they enable.
     *
     * @generated from protobuf rpc: GetPreferenceTemplates
     */
    getPreferenceTemplates(input: GetPreferenceTemplatesRequest, options?: RpcOptions): UnaryCall<GetPreferenceTemplatesRequest, GetPreferenceTemplatesResponse>;
}
/**
 * Nynorsk service for translating documents using Nynorskroboten.
 *
 * @generated from protobuf service ttab.ntb.Nynorsk
 */
export class NynorskClient implements INynorskClient, ServiceInfo {
    typeName = Nynorsk.typeName;
    methods = Nynorsk.methods;
    options = Nynorsk.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Translate translates a document between Scandinavian languages.
     *
     * @generated from protobuf rpc: Translate
     */
    translate(input: TranslateRequest, options?: RpcOptions): UnaryCall<TranslateRequest, TranslateResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<TranslateRequest, TranslateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetLanguagePrefs returns the available optional language forms.
     *
     * @generated from protobuf rpc: GetLanguagePrefs
     */
    getLanguagePrefs(input: GetLanguagePrefsRequest, options?: RpcOptions): UnaryCall<GetLanguagePrefsRequest, GetLanguagePrefsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLanguagePrefsRequest, GetLanguagePrefsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetDocumentFormats returns the supported document formats.
     *
     * @generated from protobuf rpc: GetDocumentFormats
     */
    getDocumentFormats(input: GetDocumentFormatsRequest, options?: RpcOptions): UnaryCall<GetDocumentFormatsRequest, GetDocumentFormatsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDocumentFormatsRequest, GetDocumentFormatsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetPreferenceTemplates returns the available preference templates and the
     * language forms they enable.
     *
     * @generated from protobuf rpc: GetPreferenceTemplates
     */
    getPreferenceTemplates(input: GetPreferenceTemplatesRequest, options?: RpcOptions): UnaryCall<GetPreferenceTemplatesRequest, GetPreferenceTemplatesResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPreferenceTemplatesRequest, GetPreferenceTemplatesResponse>("unary", this._transport, method, opt, input);
    }
}
