/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "intelligence/service.proto" (package "ttab.intelligence", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Comments } from "./service";
import type { SetThreadACLResponse } from "./service";
import type { SetThreadACLRequest } from "./service";
import type { DeleteCommentResponse } from "./service";
import type { DeleteCommentRequest } from "./service";
import type { GetCommentResponse } from "./service";
import type { GetCommentRequest } from "./service";
import type { ListThreadsResponse } from "./service";
import type { ListThreadsRequest } from "./service";
import type { GetThreadResponse } from "./service";
import type { GetThreadRequest } from "./service";
import type { PostCommentResponse } from "./service";
import type { PostCommentRequest } from "./service";
import { Prompts } from "./service";
import type { TestPromptResponse } from "./service";
import type { TestPromptRequest } from "./service";
import type { GetPromptResponse } from "./service";
import type { GetPromptRequest } from "./service";
import type { ListPromptsResponse } from "./service";
import type { ListPromptsRequest } from "./service";
import { Embeddings } from "./service";
import type { SemanticSearchResponse } from "./service";
import type { SemanticSearchRequest } from "./service";
import { Translate } from "./service";
import type { TranslateDocumentResponse } from "./service";
import type { TranslateDocumentRequest } from "./service";
import type { RemoveGenerativeTranslatorResponse } from "./service";
import type { RemoveGenerativeTranslatorRequest } from "./service";
import type { ConfigureGenerativeTranslatorResponse } from "./service";
import type { ConfigureGenerativeTranslatorRequest } from "./service";
import type { GetTranslationModelsResponse } from "./service";
import type { GetTranslationModelsRequest } from "./service";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Generate } from "./service";
import type { GetResultResponse } from "./service";
import type { GetResultRequest } from "./service";
import type { WaitForJobsResponse } from "./service";
import type { WaitForJobsRequest } from "./service";
import type { ListJobsResponse } from "./service";
import type { ListJobsRequest } from "./service";
import type { TextResponse } from "./service";
import type { TextRequest } from "./service";
import type { LanguageFeedbackResponse } from "./service";
import type { LanguageFeedbackRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DocumentFromTextResponse } from "./service";
import type { DocumentFromTextRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Generate provides AI-powered content generation from text inputs.
 *
 * @generated from protobuf service ttab.intelligence.Generate
 */
export interface IGenerateClient {
    /**
     * DocumentFromText creates a document from an input text.
     *
     * @generated from protobuf rpc: DocumentFromText
     */
    documentFromText(input: DocumentFromTextRequest, options?: RpcOptions): UnaryCall<DocumentFromTextRequest, DocumentFromTextResponse>;
    /**
     * LanguageFeedback gives feedback on a text.
     *
     * @generated from protobuf rpc: LanguageFeedback
     */
    languageFeedback(input: LanguageFeedbackRequest, options?: RpcOptions): UnaryCall<LanguageFeedbackRequest, LanguageFeedbackResponse>;
    /**
     * Text generates text from a input.
     *
     * @generated from protobuf rpc: Text
     */
    text(input: TextRequest, options?: RpcOptions): UnaryCall<TextRequest, TextResponse>;
    /**
     * ListJobs that have been submitted.
     *
     * @generated from protobuf rpc: ListJobs
     */
    listJobs(input: ListJobsRequest, options?: RpcOptions): UnaryCall<ListJobsRequest, ListJobsResponse>;
    /**
     * WaitForJobs is used to wait for status updates for a set of jobs.
     *
     * @generated from protobuf rpc: WaitForJobs
     */
    waitForJobs(input: WaitForJobsRequest, options?: RpcOptions): UnaryCall<WaitForJobsRequest, WaitForJobsResponse>;
    /**
     * GetResult returns the result for a job.
     *
     * @generated from protobuf rpc: GetResult
     */
    getResult(input: GetResultRequest, options?: RpcOptions): UnaryCall<GetResultRequest, GetResultResponse>;
}
/**
 * Generate provides AI-powered content generation from text inputs.
 *
 * @generated from protobuf service ttab.intelligence.Generate
 */
export class GenerateClient implements IGenerateClient, ServiceInfo {
    typeName = Generate.typeName;
    methods = Generate.methods;
    options = Generate.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * DocumentFromText creates a document from an input text.
     *
     * @generated from protobuf rpc: DocumentFromText
     */
    documentFromText(input: DocumentFromTextRequest, options?: RpcOptions): UnaryCall<DocumentFromTextRequest, DocumentFromTextResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DocumentFromTextRequest, DocumentFromTextResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * LanguageFeedback gives feedback on a text.
     *
     * @generated from protobuf rpc: LanguageFeedback
     */
    languageFeedback(input: LanguageFeedbackRequest, options?: RpcOptions): UnaryCall<LanguageFeedbackRequest, LanguageFeedbackResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LanguageFeedbackRequest, LanguageFeedbackResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Text generates text from a input.
     *
     * @generated from protobuf rpc: Text
     */
    text(input: TextRequest, options?: RpcOptions): UnaryCall<TextRequest, TextResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TextRequest, TextResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListJobs that have been submitted.
     *
     * @generated from protobuf rpc: ListJobs
     */
    listJobs(input: ListJobsRequest, options?: RpcOptions): UnaryCall<ListJobsRequest, ListJobsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListJobsRequest, ListJobsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * WaitForJobs is used to wait for status updates for a set of jobs.
     *
     * @generated from protobuf rpc: WaitForJobs
     */
    waitForJobs(input: WaitForJobsRequest, options?: RpcOptions): UnaryCall<WaitForJobsRequest, WaitForJobsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<WaitForJobsRequest, WaitForJobsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetResult returns the result for a job.
     *
     * @generated from protobuf rpc: GetResult
     */
    getResult(input: GetResultRequest, options?: RpcOptions): UnaryCall<GetResultRequest, GetResultResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetResultRequest, GetResultResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Translate manages translation models and their configuration.
 *
 * @generated from protobuf service ttab.intelligence.Translate
 */
export interface ITranslateClient {
    /**
     * GetTranslationModels lists all available translation models.
     *
     * @generated from protobuf rpc: GetTranslationModels
     */
    getTranslationModels(input: GetTranslationModelsRequest, options?: RpcOptions): UnaryCall<GetTranslationModelsRequest, GetTranslationModelsResponse>;
    /**
     * ConfigureGenerativeTranslator creates or updates a generative translation
     * model configuration.
     *
     * @generated from protobuf rpc: ConfigureGenerativeTranslator
     */
    configureGenerativeTranslator(input: ConfigureGenerativeTranslatorRequest, options?: RpcOptions): UnaryCall<ConfigureGenerativeTranslatorRequest, ConfigureGenerativeTranslatorResponse>;
    /**
     * RemoveGenerativeTranslator removes a generative translation model
     * configuration.
     *
     * @generated from protobuf rpc: RemoveGenerativeTranslator
     */
    removeGenerativeTranslator(input: RemoveGenerativeTranslatorRequest, options?: RpcOptions): UnaryCall<RemoveGenerativeTranslatorRequest, RemoveGenerativeTranslatorResponse>;
    /**
     * TranslateDocument translates the content of a document to a target
     * language. Returns the translated document with original content
     * preserved in a meta block.
     *
     * @generated from protobuf rpc: TranslateDocument
     */
    translateDocument(input: TranslateDocumentRequest, options?: RpcOptions): UnaryCall<TranslateDocumentRequest, TranslateDocumentResponse>;
}
/**
 * Translate manages translation models and their configuration.
 *
 * @generated from protobuf service ttab.intelligence.Translate
 */
export class TranslateClient implements ITranslateClient, ServiceInfo {
    typeName = Translate.typeName;
    methods = Translate.methods;
    options = Translate.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetTranslationModels lists all available translation models.
     *
     * @generated from protobuf rpc: GetTranslationModels
     */
    getTranslationModels(input: GetTranslationModelsRequest, options?: RpcOptions): UnaryCall<GetTranslationModelsRequest, GetTranslationModelsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTranslationModelsRequest, GetTranslationModelsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ConfigureGenerativeTranslator creates or updates a generative translation
     * model configuration.
     *
     * @generated from protobuf rpc: ConfigureGenerativeTranslator
     */
    configureGenerativeTranslator(input: ConfigureGenerativeTranslatorRequest, options?: RpcOptions): UnaryCall<ConfigureGenerativeTranslatorRequest, ConfigureGenerativeTranslatorResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConfigureGenerativeTranslatorRequest, ConfigureGenerativeTranslatorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RemoveGenerativeTranslator removes a generative translation model
     * configuration.
     *
     * @generated from protobuf rpc: RemoveGenerativeTranslator
     */
    removeGenerativeTranslator(input: RemoveGenerativeTranslatorRequest, options?: RpcOptions): UnaryCall<RemoveGenerativeTranslatorRequest, RemoveGenerativeTranslatorResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveGenerativeTranslatorRequest, RemoveGenerativeTranslatorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * TranslateDocument translates the content of a document to a target
     * language. Returns the translated document with original content
     * preserved in a meta block.
     *
     * @generated from protobuf rpc: TranslateDocument
     */
    translateDocument(input: TranslateDocumentRequest, options?: RpcOptions): UnaryCall<TranslateDocumentRequest, TranslateDocumentResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<TranslateDocumentRequest, TranslateDocumentResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Embeddings provides semantic search across embedded documents.
 *
 * @generated from protobuf service ttab.intelligence.Embeddings
 */
export interface IEmbeddingsClient {
    /**
     * Search performs a semantic search across embedded documents.
     *
     * @generated from protobuf rpc: Search
     */
    search(input: SemanticSearchRequest, options?: RpcOptions): UnaryCall<SemanticSearchRequest, SemanticSearchResponse>;
}
/**
 * Embeddings provides semantic search across embedded documents.
 *
 * @generated from protobuf service ttab.intelligence.Embeddings
 */
export class EmbeddingsClient implements IEmbeddingsClient, ServiceInfo {
    typeName = Embeddings.typeName;
    methods = Embeddings.methods;
    options = Embeddings.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Search performs a semantic search across embedded documents.
     *
     * @generated from protobuf rpc: Search
     */
    search(input: SemanticSearchRequest, options?: RpcOptions): UnaryCall<SemanticSearchRequest, SemanticSearchResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SemanticSearchRequest, SemanticSearchResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Prompts provides management and testing of prompt documents.
 *
 * @generated from protobuf service ttab.intelligence.Prompts
 */
export interface IPromptsClient {
    /**
     * ListPrompts lists prompt documents from the repository.
     *
     * @generated from protobuf rpc: ListPrompts
     */
    listPrompts(input: ListPromptsRequest, options?: RpcOptions): UnaryCall<ListPromptsRequest, ListPromptsResponse>;
    /**
     * GetPrompt retrieves a prompt document with its rendered content.
     *
     * @generated from protobuf rpc: GetPrompt
     */
    getPrompt(input: GetPromptRequest, options?: RpcOptions): UnaryCall<GetPromptRequest, GetPromptResponse>;
    /**
     * TestPrompt runs a prompt with test input and returns the result.
     *
     * @generated from protobuf rpc: TestPrompt
     */
    testPrompt(input: TestPromptRequest, options?: RpcOptions): UnaryCall<TestPromptRequest, TestPromptResponse>;
}
/**
 * Prompts provides management and testing of prompt documents.
 *
 * @generated from protobuf service ttab.intelligence.Prompts
 */
export class PromptsClient implements IPromptsClient, ServiceInfo {
    typeName = Prompts.typeName;
    methods = Prompts.methods;
    options = Prompts.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * ListPrompts lists prompt documents from the repository.
     *
     * @generated from protobuf rpc: ListPrompts
     */
    listPrompts(input: ListPromptsRequest, options?: RpcOptions): UnaryCall<ListPromptsRequest, ListPromptsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPromptsRequest, ListPromptsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetPrompt retrieves a prompt document with its rendered content.
     *
     * @generated from protobuf rpc: GetPrompt
     */
    getPrompt(input: GetPromptRequest, options?: RpcOptions): UnaryCall<GetPromptRequest, GetPromptResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPromptRequest, GetPromptResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * TestPrompt runs a prompt with test input and returns the result.
     *
     * @generated from protobuf rpc: TestPrompt
     */
    testPrompt(input: TestPromptRequest, options?: RpcOptions): UnaryCall<TestPromptRequest, TestPromptResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TestPromptRequest, TestPromptResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * Comments provides threaded commenting for research documents.
 *
 * @generated from protobuf service ttab.intelligence.Comments
 */
export interface ICommentsClient {
    /**
     * PostComment posts a comment to a thread. If thread_uuid is empty, a new
     * thread is created.
     *
     * @generated from protobuf rpc: PostComment
     */
    postComment(input: PostCommentRequest, options?: RpcOptions): UnaryCall<PostCommentRequest, PostCommentResponse>;
    /**
     * GetThread returns a thread with all its comments and replies.
     *
     * @generated from protobuf rpc: GetThread
     */
    getThread(input: GetThreadRequest, options?: RpcOptions): UnaryCall<GetThreadRequest, GetThreadResponse>;
    /**
     * ListThreads returns metadata for the given thread UUIDs.
     *
     * @generated from protobuf rpc: ListThreads
     */
    listThreads(input: ListThreadsRequest, options?: RpcOptions): UnaryCall<ListThreadsRequest, ListThreadsResponse>;
    /**
     * GetComment returns a single comment.
     *
     * @generated from protobuf rpc: GetComment
     */
    getComment(input: GetCommentRequest, options?: RpcOptions): UnaryCall<GetCommentRequest, GetCommentResponse>;
    /**
     * DeleteComment soft-deletes a comment.
     *
     * @generated from protobuf rpc: DeleteComment
     */
    deleteComment(input: DeleteCommentRequest, options?: RpcOptions): UnaryCall<DeleteCommentRequest, DeleteCommentResponse>;
    /**
     * SetThreadACL replaces the access control list for a thread.
     *
     * @generated from protobuf rpc: SetThreadACL
     */
    setThreadACL(input: SetThreadACLRequest, options?: RpcOptions): UnaryCall<SetThreadACLRequest, SetThreadACLResponse>;
}
/**
 * Comments provides threaded commenting for research documents.
 *
 * @generated from protobuf service ttab.intelligence.Comments
 */
export class CommentsClient implements ICommentsClient, ServiceInfo {
    typeName = Comments.typeName;
    methods = Comments.methods;
    options = Comments.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * PostComment posts a comment to a thread. If thread_uuid is empty, a new
     * thread is created.
     *
     * @generated from protobuf rpc: PostComment
     */
    postComment(input: PostCommentRequest, options?: RpcOptions): UnaryCall<PostCommentRequest, PostCommentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostCommentRequest, PostCommentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetThread returns a thread with all its comments and replies.
     *
     * @generated from protobuf rpc: GetThread
     */
    getThread(input: GetThreadRequest, options?: RpcOptions): UnaryCall<GetThreadRequest, GetThreadResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetThreadRequest, GetThreadResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListThreads returns metadata for the given thread UUIDs.
     *
     * @generated from protobuf rpc: ListThreads
     */
    listThreads(input: ListThreadsRequest, options?: RpcOptions): UnaryCall<ListThreadsRequest, ListThreadsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListThreadsRequest, ListThreadsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetComment returns a single comment.
     *
     * @generated from protobuf rpc: GetComment
     */
    getComment(input: GetCommentRequest, options?: RpcOptions): UnaryCall<GetCommentRequest, GetCommentResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCommentRequest, GetCommentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteComment soft-deletes a comment.
     *
     * @generated from protobuf rpc: DeleteComment
     */
    deleteComment(input: DeleteCommentRequest, options?: RpcOptions): UnaryCall<DeleteCommentRequest, DeleteCommentResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCommentRequest, DeleteCommentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * SetThreadACL replaces the access control list for a thread.
     *
     * @generated from protobuf rpc: SetThreadACL
     */
    setThreadACL(input: SetThreadACLRequest, options?: RpcOptions): UnaryCall<SetThreadACLRequest, SetThreadACLResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetThreadACLRequest, SetThreadACLResponse>("unary", this._transport, method, opt, input);
    }
}
