/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "genai/service.proto" (package "ttab.genai", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Generate } from "./service";
import type { GetResultResponse } from "./service";
import type { GetResultRequest } from "./service";
import type { WaitForJobsResponse } from "./service";
import type { WaitForJobsRequest } from "./service";
import type { ListJobsResponse } from "./service";
import type { ListJobsRequest } from "./service";
import type { TextResponse } from "./service";
import type { TextRequest } from "./service";
import type { LanguageFeedbackResponse } from "./service";
import type { LanguageFeedbackRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DocumentFromTextResponse } from "./service";
import type { DocumentFromTextRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ttab.genai.Generate
 */
export interface IGenerateClient {
    /**
     * DocumentFromText creates a document from an input text.
     *
     * @generated from protobuf rpc: DocumentFromText
     */
    documentFromText(input: DocumentFromTextRequest, options?: RpcOptions): UnaryCall<DocumentFromTextRequest, DocumentFromTextResponse>;
    /**
     * LanguageFeedback gives feedback on a text.
     *
     * @generated from protobuf rpc: LanguageFeedback
     */
    languageFeedback(input: LanguageFeedbackRequest, options?: RpcOptions): UnaryCall<LanguageFeedbackRequest, LanguageFeedbackResponse>;
    /**
     * Text generates text from a input.
     *
     * @generated from protobuf rpc: Text
     */
    text(input: TextRequest, options?: RpcOptions): UnaryCall<TextRequest, TextResponse>;
    /**
     * ListJobs that have been submitted.
     *
     * @generated from protobuf rpc: ListJobs
     */
    listJobs(input: ListJobsRequest, options?: RpcOptions): UnaryCall<ListJobsRequest, ListJobsResponse>;
    /**
     * WaitForJobs is used to wait for status updates for a set of jobs.
     *
     * @generated from protobuf rpc: WaitForJobs
     */
    waitForJobs(input: WaitForJobsRequest, options?: RpcOptions): UnaryCall<WaitForJobsRequest, WaitForJobsResponse>;
    /**
     * GetResult returns the result for a job.
     *
     * @generated from protobuf rpc: GetResult
     */
    getResult(input: GetResultRequest, options?: RpcOptions): UnaryCall<GetResultRequest, GetResultResponse>;
}
/**
 * @generated from protobuf service ttab.genai.Generate
 */
export class GenerateClient implements IGenerateClient, ServiceInfo {
    typeName = Generate.typeName;
    methods = Generate.methods;
    options = Generate.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * DocumentFromText creates a document from an input text.
     *
     * @generated from protobuf rpc: DocumentFromText
     */
    documentFromText(input: DocumentFromTextRequest, options?: RpcOptions): UnaryCall<DocumentFromTextRequest, DocumentFromTextResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DocumentFromTextRequest, DocumentFromTextResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * LanguageFeedback gives feedback on a text.
     *
     * @generated from protobuf rpc: LanguageFeedback
     */
    languageFeedback(input: LanguageFeedbackRequest, options?: RpcOptions): UnaryCall<LanguageFeedbackRequest, LanguageFeedbackResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LanguageFeedbackRequest, LanguageFeedbackResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Text generates text from a input.
     *
     * @generated from protobuf rpc: Text
     */
    text(input: TextRequest, options?: RpcOptions): UnaryCall<TextRequest, TextResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TextRequest, TextResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListJobs that have been submitted.
     *
     * @generated from protobuf rpc: ListJobs
     */
    listJobs(input: ListJobsRequest, options?: RpcOptions): UnaryCall<ListJobsRequest, ListJobsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListJobsRequest, ListJobsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * WaitForJobs is used to wait for status updates for a set of jobs.
     *
     * @generated from protobuf rpc: WaitForJobs
     */
    waitForJobs(input: WaitForJobsRequest, options?: RpcOptions): UnaryCall<WaitForJobsRequest, WaitForJobsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<WaitForJobsRequest, WaitForJobsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetResult returns the result for a job.
     *
     * @generated from protobuf rpc: GetResult
     */
    getResult(input: GetResultRequest, options?: RpcOptions): UnaryCall<GetResultRequest, GetResultResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetResultRequest, GetResultResponse>("unary", this._transport, method, opt, input);
    }
}
