/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "genai/service.proto" (package "ttab.genai", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Document } from "../newsdoc/newsdoc";
import { Block } from "../newsdoc/newsdoc";
/**
 * @generated from protobuf message ttab.genai.DocumentFromTextRequest
 */
export interface DocumentFromTextRequest {
    /**
     * Model is the URI of the model to use.
     *
     * @generated from protobuf field: string model = 1
     */
    model: string;
    /**
     * Text to send as input.
     *
     * @generated from protobuf field: string text = 2
     */
    text: string;
    /**
     * UUID to set for the document.
     *
     * @generated from protobuf field: string uuid = 3
     */
    uuid: string;
    /**
     * URI to set for the document.
     *
     * @generated from protobuf field: string uri = 4
     */
    uri: string;
    /**
     * AdditionalLinks that should be added to the generated document.
     *
     * @generated from protobuf field: repeated newsdoc.Block additionalLinks = 5
     */
    additionalLinks: Block[];
    /**
     * AdditionalMeta blocks that should be added to the generated document.
     *
     * @generated from protobuf field: repeated newsdoc.Block additionalMeta = 6
     */
    additionalMeta: Block[];
    /**
     * AsyncTimeoutSeconds is the time after which a JobID will be returned
     * instead of a direct result. Optional, defaults to no timeout.
     *
     * @generated from protobuf field: int64 async_timeout_seconds = 7
     */
    asyncTimeoutSeconds: bigint;
}
/**
 * @generated from protobuf message ttab.genai.DocumentFromTextResponse
 */
export interface DocumentFromTextResponse {
    /**
     * JobID that identifies the job.
     *
     * @generated from protobuf field: int64 job_id = 1
     */
    jobId: bigint;
    /**
     * Document that was generated.
     *
     * @generated from protobuf field: newsdoc.Document document = 2
     */
    document?: Document;
}
/**
 * @generated from protobuf message ttab.genai.LanguageFeedbackRequest
 */
export interface LanguageFeedbackRequest {
    /**
     * Model is the URI of the model to use.
     *
     * @generated from protobuf field: string model = 1
     */
    model: string;
    /**
     * Paragraphs to review. Feedback will reference these paragraphs by
     * index. Optional, but either paragraphs, document_uuid, or document must be
     * set.
     *
     * @generated from protobuf field: repeated string paragraphs = 2
     */
    paragraphs: string[];
    /**
     * DocumentUUID of the document to give feedback on. The "core/text" content
     * blocks will be extracted and the feedback will reference them by
     * index. Optional, but either paragraphs, document_uuid, or document must be
     * set.
     *
     * @generated from protobuf field: string document_uuid = 3
     */
    documentUuid: string;
    /**
     * Document is the document to give feedback on. The "core/text" content
     * blocks will be extracted and the feedback will reference them by
     * index. Optional, but either paragraphs, document_uuid, or document must be
     * set.
     *
     * @generated from protobuf field: newsdoc.Document document = 4
     */
    document?: Document;
    /**
     * AsyncTimeoutSeconds is the time after which a JobID will be returned
     * instead of a direct result. Optional, defaults to no timeout.
     *
     * @generated from protobuf field: int64 async_timeout_seconds = 5
     */
    asyncTimeoutSeconds: bigint;
}
/**
 * @generated from protobuf message ttab.genai.LanguageFeedbackResponse
 */
export interface LanguageFeedbackResponse {
    /**
     * JobID that identifies the created job.
     *
     * @generated from protobuf field: int64 job_id = 1
     */
    jobId: bigint;
    /**
     * Feedback items.
     *
     * @generated from protobuf field: repeated ttab.genai.LanguageFeedback feedback = 2
     */
    feedback: LanguageFeedback[];
    /**
     * Paragraphs are the paragraphs being referenced in the feedback.
     *
     * @generated from protobuf field: repeated string paragraphs = 3
     */
    paragraphs: string[];
}
/**
 * @generated from protobuf message ttab.genai.LanguageFeedback
 */
export interface LanguageFeedback {
    /**
     * Paragraph index. Set to -1 if the feedback couldn't be connected to a
     * specific paragraph.
     *
     * @generated from protobuf field: int64 paragraph = 1
     */
    paragraph: bigint;
    /**
     * Original text excerpt.
     *
     * @generated from protobuf field: string original = 2
     */
    original: string;
    /**
     * Suggestion for new text.
     *
     * @generated from protobuf field: string suggestion = 4
     */
    suggestion: string;
    /**
     * Motivation for the change.
     *
     * @generated from protobuf field: string motivation = 5
     */
    motivation: string;
    /**
     * ParagraphID is present when the feedback is performed on a document and the
     * text block had a ID.
     *
     * @generated from protobuf field: string paragraph_id = 6
     */
    paragraphId: string;
}
/**
 * @generated from protobuf message ttab.genai.TextRequest
 */
export interface TextRequest {
    /**
     * Model is the URI of the model to use.
     *
     * @generated from protobuf field: string model = 1
     */
    model: string;
    /**
     * Text to send as input.
     *
     * @generated from protobuf field: string text = 2
     */
    text: string;
    /**
     * ParseText tries to parse the generated text into blocks if set to true.
     *
     * @generated from protobuf field: bool parse_text = 3
     */
    parseText: boolean;
    /**
     * CharacterCount sets a target for how long the generated text should be.
     *
     * @generated from protobuf field: int32 character_count = 4
     */
    characterCount: number;
    /**
     * AsyncTimeoutSeconds is the time after which a JobID will be returned
     * instead of a direct result. Optional, defaults to no timeout.
     *
     * @generated from protobuf field: int64 async_timeout_seconds = 5
     */
    asyncTimeoutSeconds: bigint;
}
/**
 * @generated from protobuf message ttab.genai.TextResponse
 */
export interface TextResponse {
    /**
     * JobID that identifies the created job.
     *
     * @generated from protobuf field: int64 job_id = 1
     */
    jobId: bigint;
    /**
     * Text is the generated text.
     *
     * @generated from protobuf field: string text = 2
     */
    text: string;
    /**
     * Contet blocks generated from the text.
     *
     * @generated from protobuf field: repeated newsdoc.Block content = 3
     */
    content: Block[];
}
/**
 * @generated from protobuf message ttab.genai.ListJobsRequest
 */
export interface ListJobsRequest {
    /**
     * After lists jobs after the given ID. Optional, omit to get latest.
     *
     * @generated from protobuf field: int64 after = 1
     */
    after: bigint;
}
/**
 * @generated from protobuf message ttab.genai.ListJobsResponse
 */
export interface ListJobsResponse {
    /**
     * @generated from protobuf field: repeated ttab.genai.JobReference jobs = 1
     */
    jobs: JobReference[];
}
/**
 * @generated from protobuf message ttab.genai.WaitForJobsRequest
 */
export interface WaitForJobsRequest {
    /**
     * Jobs and the currently known version that the client is waiting
     * for. Required.
     *
     * @generated from protobuf field: map<int64, int64> jobs = 1
     */
    jobs: {
        [key: string]: bigint;
    };
    /**
     * MaxWaitSec is the maximum time to wait for updates. Optional, defaults to
     * 10.
     *
     * @generated from protobuf field: int64 max_wait_sec = 2
     */
    maxWaitSec: bigint;
}
/**
 * @generated from protobuf message ttab.genai.WaitForJobsResponse
 */
export interface WaitForJobsResponse {
    /**
     * Updated jobs, can be empty if the wait timed out without any updates.
     *
     * @generated from protobuf field: repeated ttab.genai.JobReference updated = 1
     */
    updated: JobReference[];
}
/**
 * @generated from protobuf message ttab.genai.GetResultRequest
 */
export interface GetResultRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
}
/**
 * @generated from protobuf message ttab.genai.JobReference
 */
export interface JobReference {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: ttab.genai.JobStatus status = 2
     */
    status: JobStatus;
}
/**
 * @generated from protobuf message ttab.genai.GetResultResponse
 */
export interface GetResultResponse {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: string model = 2
     */
    model: string;
    /**
     * @generated from protobuf field: ttab.genai.JobType type = 3
     */
    type: JobType;
    /**
     * @generated from protobuf field: ttab.genai.JobStatus status = 4
     */
    status: JobStatus;
    /**
     * @generated from protobuf field: string error_code = 5
     */
    errorCode: string;
    /**
     * @generated from protobuf field: string error = 6
     */
    error: string;
    /**
     * @generated from protobuf field: newsdoc.Document document = 7
     */
    document?: Document;
    /**
     * @generated from protobuf field: ttab.genai.LanguageFeedback feedback = 8
     */
    feedback?: LanguageFeedback;
}
/**
 * @generated from protobuf enum ttab.genai.JobStatus
 */
export enum JobStatus {
    /**
     * @generated from protobuf enum value: STATUS_UNKNOWN = 0;
     */
    STATUS_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: STATUS_DONE = 1;
     */
    STATUS_DONE = 1,
    /**
     * @generated from protobuf enum value: STATUS_FAILED = 2;
     */
    STATUS_FAILED = 2
}
/**
 * @generated from protobuf enum ttab.genai.JobType
 */
export enum JobType {
    /**
     * @generated from protobuf enum value: JOB_TYPE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: JOB_TYPE_DOCUMENT = 1;
     */
    DOCUMENT = 1,
    /**
     * @generated from protobuf enum value: JOB_TYPE_FEEDBACK = 2;
     */
    FEEDBACK = 2,
    /**
     * @generated from protobuf enum value: JOB_TYPE_TEXT = 3;
     */
    TEXT = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class DocumentFromTextRequest$Type extends MessageType<DocumentFromTextRequest> {
    constructor() {
        super("ttab.genai.DocumentFromTextRequest", [
            { no: 1, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "additionalLinks", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Block },
            { no: 6, name: "additionalMeta", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Block },
            { no: 7, name: "async_timeout_seconds", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DocumentFromTextRequest>): DocumentFromTextRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.model = "";
        message.text = "";
        message.uuid = "";
        message.uri = "";
        message.additionalLinks = [];
        message.additionalMeta = [];
        message.asyncTimeoutSeconds = 0n;
        if (value !== undefined)
            reflectionMergePartial<DocumentFromTextRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DocumentFromTextRequest): DocumentFromTextRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string model */ 1:
                    message.model = reader.string();
                    break;
                case /* string text */ 2:
                    message.text = reader.string();
                    break;
                case /* string uuid */ 3:
                    message.uuid = reader.string();
                    break;
                case /* string uri */ 4:
                    message.uri = reader.string();
                    break;
                case /* repeated newsdoc.Block additionalLinks */ 5:
                    message.additionalLinks.push(Block.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated newsdoc.Block additionalMeta */ 6:
                    message.additionalMeta.push(Block.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int64 async_timeout_seconds */ 7:
                    message.asyncTimeoutSeconds = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DocumentFromTextRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string model = 1; */
        if (message.model !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.model);
        /* string text = 2; */
        if (message.text !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.text);
        /* string uuid = 3; */
        if (message.uuid !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.uuid);
        /* string uri = 4; */
        if (message.uri !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.uri);
        /* repeated newsdoc.Block additionalLinks = 5; */
        for (let i = 0; i < message.additionalLinks.length; i++)
            Block.internalBinaryWrite(message.additionalLinks[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* repeated newsdoc.Block additionalMeta = 6; */
        for (let i = 0; i < message.additionalMeta.length; i++)
            Block.internalBinaryWrite(message.additionalMeta[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* int64 async_timeout_seconds = 7; */
        if (message.asyncTimeoutSeconds !== 0n)
            writer.tag(7, WireType.Varint).int64(message.asyncTimeoutSeconds);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.DocumentFromTextRequest
 */
export const DocumentFromTextRequest = new DocumentFromTextRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DocumentFromTextResponse$Type extends MessageType<DocumentFromTextResponse> {
    constructor() {
        super("ttab.genai.DocumentFromTextResponse", [
            { no: 1, name: "job_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "document", kind: "message", T: () => Document }
        ]);
    }
    create(value?: PartialMessage<DocumentFromTextResponse>): DocumentFromTextResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = 0n;
        if (value !== undefined)
            reflectionMergePartial<DocumentFromTextResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DocumentFromTextResponse): DocumentFromTextResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 job_id */ 1:
                    message.jobId = reader.int64().toBigInt();
                    break;
                case /* newsdoc.Document document */ 2:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DocumentFromTextResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 job_id = 1; */
        if (message.jobId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.jobId);
        /* newsdoc.Document document = 2; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.DocumentFromTextResponse
 */
export const DocumentFromTextResponse = new DocumentFromTextResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LanguageFeedbackRequest$Type extends MessageType<LanguageFeedbackRequest> {
    constructor() {
        super("ttab.genai.LanguageFeedbackRequest", [
            { no: 1, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "paragraphs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "document_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "document", kind: "message", T: () => Document },
            { no: 5, name: "async_timeout_seconds", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<LanguageFeedbackRequest>): LanguageFeedbackRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.model = "";
        message.paragraphs = [];
        message.documentUuid = "";
        message.asyncTimeoutSeconds = 0n;
        if (value !== undefined)
            reflectionMergePartial<LanguageFeedbackRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LanguageFeedbackRequest): LanguageFeedbackRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string model */ 1:
                    message.model = reader.string();
                    break;
                case /* repeated string paragraphs */ 2:
                    message.paragraphs.push(reader.string());
                    break;
                case /* string document_uuid */ 3:
                    message.documentUuid = reader.string();
                    break;
                case /* newsdoc.Document document */ 4:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                case /* int64 async_timeout_seconds */ 5:
                    message.asyncTimeoutSeconds = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LanguageFeedbackRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string model = 1; */
        if (message.model !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.model);
        /* repeated string paragraphs = 2; */
        for (let i = 0; i < message.paragraphs.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.paragraphs[i]);
        /* string document_uuid = 3; */
        if (message.documentUuid !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.documentUuid);
        /* newsdoc.Document document = 4; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* int64 async_timeout_seconds = 5; */
        if (message.asyncTimeoutSeconds !== 0n)
            writer.tag(5, WireType.Varint).int64(message.asyncTimeoutSeconds);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.LanguageFeedbackRequest
 */
export const LanguageFeedbackRequest = new LanguageFeedbackRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LanguageFeedbackResponse$Type extends MessageType<LanguageFeedbackResponse> {
    constructor() {
        super("ttab.genai.LanguageFeedbackResponse", [
            { no: 1, name: "job_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "feedback", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LanguageFeedback },
            { no: 3, name: "paragraphs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LanguageFeedbackResponse>): LanguageFeedbackResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = 0n;
        message.feedback = [];
        message.paragraphs = [];
        if (value !== undefined)
            reflectionMergePartial<LanguageFeedbackResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LanguageFeedbackResponse): LanguageFeedbackResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 job_id */ 1:
                    message.jobId = reader.int64().toBigInt();
                    break;
                case /* repeated ttab.genai.LanguageFeedback feedback */ 2:
                    message.feedback.push(LanguageFeedback.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated string paragraphs */ 3:
                    message.paragraphs.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LanguageFeedbackResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 job_id = 1; */
        if (message.jobId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.jobId);
        /* repeated ttab.genai.LanguageFeedback feedback = 2; */
        for (let i = 0; i < message.feedback.length; i++)
            LanguageFeedback.internalBinaryWrite(message.feedback[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string paragraphs = 3; */
        for (let i = 0; i < message.paragraphs.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.paragraphs[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.LanguageFeedbackResponse
 */
export const LanguageFeedbackResponse = new LanguageFeedbackResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LanguageFeedback$Type extends MessageType<LanguageFeedback> {
    constructor() {
        super("ttab.genai.LanguageFeedback", [
            { no: 1, name: "paragraph", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "original", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "suggestion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "motivation", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "paragraph_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LanguageFeedback>): LanguageFeedback {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paragraph = 0n;
        message.original = "";
        message.suggestion = "";
        message.motivation = "";
        message.paragraphId = "";
        if (value !== undefined)
            reflectionMergePartial<LanguageFeedback>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LanguageFeedback): LanguageFeedback {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 paragraph */ 1:
                    message.paragraph = reader.int64().toBigInt();
                    break;
                case /* string original */ 2:
                    message.original = reader.string();
                    break;
                case /* string suggestion */ 4:
                    message.suggestion = reader.string();
                    break;
                case /* string motivation */ 5:
                    message.motivation = reader.string();
                    break;
                case /* string paragraph_id */ 6:
                    message.paragraphId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LanguageFeedback, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 paragraph = 1; */
        if (message.paragraph !== 0n)
            writer.tag(1, WireType.Varint).int64(message.paragraph);
        /* string original = 2; */
        if (message.original !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.original);
        /* string suggestion = 4; */
        if (message.suggestion !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.suggestion);
        /* string motivation = 5; */
        if (message.motivation !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.motivation);
        /* string paragraph_id = 6; */
        if (message.paragraphId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.paragraphId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.LanguageFeedback
 */
export const LanguageFeedback = new LanguageFeedback$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TextRequest$Type extends MessageType<TextRequest> {
    constructor() {
        super("ttab.genai.TextRequest", [
            { no: 1, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "parse_text", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "character_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "async_timeout_seconds", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<TextRequest>): TextRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.model = "";
        message.text = "";
        message.parseText = false;
        message.characterCount = 0;
        message.asyncTimeoutSeconds = 0n;
        if (value !== undefined)
            reflectionMergePartial<TextRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TextRequest): TextRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string model */ 1:
                    message.model = reader.string();
                    break;
                case /* string text */ 2:
                    message.text = reader.string();
                    break;
                case /* bool parse_text */ 3:
                    message.parseText = reader.bool();
                    break;
                case /* int32 character_count */ 4:
                    message.characterCount = reader.int32();
                    break;
                case /* int64 async_timeout_seconds */ 5:
                    message.asyncTimeoutSeconds = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TextRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string model = 1; */
        if (message.model !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.model);
        /* string text = 2; */
        if (message.text !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.text);
        /* bool parse_text = 3; */
        if (message.parseText !== false)
            writer.tag(3, WireType.Varint).bool(message.parseText);
        /* int32 character_count = 4; */
        if (message.characterCount !== 0)
            writer.tag(4, WireType.Varint).int32(message.characterCount);
        /* int64 async_timeout_seconds = 5; */
        if (message.asyncTimeoutSeconds !== 0n)
            writer.tag(5, WireType.Varint).int64(message.asyncTimeoutSeconds);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.TextRequest
 */
export const TextRequest = new TextRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TextResponse$Type extends MessageType<TextResponse> {
    constructor() {
        super("ttab.genai.TextResponse", [
            { no: 1, name: "job_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Block }
        ]);
    }
    create(value?: PartialMessage<TextResponse>): TextResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = 0n;
        message.text = "";
        message.content = [];
        if (value !== undefined)
            reflectionMergePartial<TextResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TextResponse): TextResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 job_id */ 1:
                    message.jobId = reader.int64().toBigInt();
                    break;
                case /* string text */ 2:
                    message.text = reader.string();
                    break;
                case /* repeated newsdoc.Block content */ 3:
                    message.content.push(Block.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TextResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 job_id = 1; */
        if (message.jobId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.jobId);
        /* string text = 2; */
        if (message.text !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.text);
        /* repeated newsdoc.Block content = 3; */
        for (let i = 0; i < message.content.length; i++)
            Block.internalBinaryWrite(message.content[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.TextResponse
 */
export const TextResponse = new TextResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListJobsRequest$Type extends MessageType<ListJobsRequest> {
    constructor() {
        super("ttab.genai.ListJobsRequest", [
            { no: 1, name: "after", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ListJobsRequest>): ListJobsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.after = 0n;
        if (value !== undefined)
            reflectionMergePartial<ListJobsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListJobsRequest): ListJobsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 after */ 1:
                    message.after = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListJobsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 after = 1; */
        if (message.after !== 0n)
            writer.tag(1, WireType.Varint).int64(message.after);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.ListJobsRequest
 */
export const ListJobsRequest = new ListJobsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListJobsResponse$Type extends MessageType<ListJobsResponse> {
    constructor() {
        super("ttab.genai.ListJobsResponse", [
            { no: 1, name: "jobs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => JobReference }
        ]);
    }
    create(value?: PartialMessage<ListJobsResponse>): ListJobsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobs = [];
        if (value !== undefined)
            reflectionMergePartial<ListJobsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListJobsResponse): ListJobsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ttab.genai.JobReference jobs */ 1:
                    message.jobs.push(JobReference.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListJobsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ttab.genai.JobReference jobs = 1; */
        for (let i = 0; i < message.jobs.length; i++)
            JobReference.internalBinaryWrite(message.jobs[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.ListJobsResponse
 */
export const ListJobsResponse = new ListJobsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WaitForJobsRequest$Type extends MessageType<WaitForJobsRequest> {
    constructor() {
        super("ttab.genai.WaitForJobsRequest", [
            { no: 1, name: "jobs", kind: "map", K: 3 /*ScalarType.INT64*/, V: { kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ } },
            { no: 2, name: "max_wait_sec", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<WaitForJobsRequest>): WaitForJobsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobs = {};
        message.maxWaitSec = 0n;
        if (value !== undefined)
            reflectionMergePartial<WaitForJobsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WaitForJobsRequest): WaitForJobsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* map<int64, int64> jobs */ 1:
                    this.binaryReadMap1(message.jobs, reader, options);
                    break;
                case /* int64 max_wait_sec */ 2:
                    message.maxWaitSec = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap1(map: WaitForJobsRequest["jobs"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof WaitForJobsRequest["jobs"] | undefined, val: WaitForJobsRequest["jobs"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.int64().toString();
                    break;
                case 2:
                    val = reader.int64().toBigInt();
                    break;
                default: throw new globalThis.Error("unknown map entry field for ttab.genai.WaitForJobsRequest.jobs");
            }
        }
        map[key ?? "0"] = val ?? 0n;
    }
    internalBinaryWrite(message: WaitForJobsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* map<int64, int64> jobs = 1; */
        for (let k of globalThis.Object.keys(message.jobs))
            writer.tag(1, WireType.LengthDelimited).fork().tag(1, WireType.Varint).int64(k).tag(2, WireType.Varint).int64(message.jobs[k]).join();
        /* int64 max_wait_sec = 2; */
        if (message.maxWaitSec !== 0n)
            writer.tag(2, WireType.Varint).int64(message.maxWaitSec);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.WaitForJobsRequest
 */
export const WaitForJobsRequest = new WaitForJobsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WaitForJobsResponse$Type extends MessageType<WaitForJobsResponse> {
    constructor() {
        super("ttab.genai.WaitForJobsResponse", [
            { no: 1, name: "updated", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => JobReference }
        ]);
    }
    create(value?: PartialMessage<WaitForJobsResponse>): WaitForJobsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.updated = [];
        if (value !== undefined)
            reflectionMergePartial<WaitForJobsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WaitForJobsResponse): WaitForJobsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ttab.genai.JobReference updated */ 1:
                    message.updated.push(JobReference.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WaitForJobsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ttab.genai.JobReference updated = 1; */
        for (let i = 0; i < message.updated.length; i++)
            JobReference.internalBinaryWrite(message.updated[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.WaitForJobsResponse
 */
export const WaitForJobsResponse = new WaitForJobsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetResultRequest$Type extends MessageType<GetResultRequest> {
    constructor() {
        super("ttab.genai.GetResultRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetResultRequest>): GetResultRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetResultRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetResultRequest): GetResultRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetResultRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.GetResultRequest
 */
export const GetResultRequest = new GetResultRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JobReference$Type extends MessageType<JobReference> {
    constructor() {
        super("ttab.genai.JobReference", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "status", kind: "enum", T: () => ["ttab.genai.JobStatus", JobStatus] }
        ]);
    }
    create(value?: PartialMessage<JobReference>): JobReference {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<JobReference>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JobReference): JobReference {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* ttab.genai.JobStatus status */ 2:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JobReference, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* ttab.genai.JobStatus status = 2; */
        if (message.status !== 0)
            writer.tag(2, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.JobReference
 */
export const JobReference = new JobReference$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetResultResponse$Type extends MessageType<GetResultResponse> {
    constructor() {
        super("ttab.genai.GetResultResponse", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["ttab.genai.JobType", JobType, "JOB_TYPE_"] },
            { no: 4, name: "status", kind: "enum", T: () => ["ttab.genai.JobStatus", JobStatus] },
            { no: 5, name: "error_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "document", kind: "message", T: () => Document },
            { no: 8, name: "feedback", kind: "message", T: () => LanguageFeedback }
        ]);
    }
    create(value?: PartialMessage<GetResultResponse>): GetResultResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.model = "";
        message.type = 0;
        message.status = 0;
        message.errorCode = "";
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<GetResultResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetResultResponse): GetResultResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string model */ 2:
                    message.model = reader.string();
                    break;
                case /* ttab.genai.JobType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* ttab.genai.JobStatus status */ 4:
                    message.status = reader.int32();
                    break;
                case /* string error_code */ 5:
                    message.errorCode = reader.string();
                    break;
                case /* string error */ 6:
                    message.error = reader.string();
                    break;
                case /* newsdoc.Document document */ 7:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                case /* ttab.genai.LanguageFeedback feedback */ 8:
                    message.feedback = LanguageFeedback.internalBinaryRead(reader, reader.uint32(), options, message.feedback);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetResultResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string model = 2; */
        if (message.model !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.model);
        /* ttab.genai.JobType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* ttab.genai.JobStatus status = 4; */
        if (message.status !== 0)
            writer.tag(4, WireType.Varint).int32(message.status);
        /* string error_code = 5; */
        if (message.errorCode !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.errorCode);
        /* string error = 6; */
        if (message.error !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.error);
        /* newsdoc.Document document = 7; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* ttab.genai.LanguageFeedback feedback = 8; */
        if (message.feedback)
            LanguageFeedback.internalBinaryWrite(message.feedback, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.genai.GetResultResponse
 */
export const GetResultResponse = new GetResultResponse$Type();
/**
 * @generated ServiceType for protobuf service ttab.genai.Generate
 */
export const Generate = new ServiceType("ttab.genai.Generate", [
    { name: "DocumentFromText", options: {}, I: DocumentFromTextRequest, O: DocumentFromTextResponse },
    { name: "LanguageFeedback", options: {}, I: LanguageFeedbackRequest, O: LanguageFeedbackResponse },
    { name: "Text", options: {}, I: TextRequest, O: TextResponse },
    { name: "ListJobs", options: {}, I: ListJobsRequest, O: ListJobsResponse },
    { name: "WaitForJobs", options: {}, I: WaitForJobsRequest, O: WaitForJobsResponse },
    { name: "GetResult", options: {}, I: GetResultRequest, O: GetResultResponse }
]);
