/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "wires/service.proto" (package "ttab.wires", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RssFeed } from "./service";
import type { DeleteFeedResponse } from "./service";
import type { DeleteFeedRequest } from "./service";
import type { UpdateFeedResponse } from "./service";
import type { UpdateFeedRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetAllFeedsResponse } from "./service";
import type { GetAllFeedsRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ttab.wires.RssFeed
 */
export interface IRssFeedClient {
    /**
     * @generated from protobuf rpc: GetAllFeeds
     */
    getAllFeeds(input: GetAllFeedsRequest, options?: RpcOptions): UnaryCall<GetAllFeedsRequest, GetAllFeedsResponse>;
    /**
     * @generated from protobuf rpc: UpdateFeed
     */
    updateFeed(input: UpdateFeedRequest, options?: RpcOptions): UnaryCall<UpdateFeedRequest, UpdateFeedResponse>;
    /**
     * @generated from protobuf rpc: DeleteFeed
     */
    deleteFeed(input: DeleteFeedRequest, options?: RpcOptions): UnaryCall<DeleteFeedRequest, DeleteFeedResponse>;
}
/**
 * @generated from protobuf service ttab.wires.RssFeed
 */
export class RssFeedClient implements IRssFeedClient, ServiceInfo {
    typeName = RssFeed.typeName;
    methods = RssFeed.methods;
    options = RssFeed.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllFeeds
     */
    getAllFeeds(input: GetAllFeedsRequest, options?: RpcOptions): UnaryCall<GetAllFeedsRequest, GetAllFeedsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllFeedsRequest, GetAllFeedsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateFeed
     */
    updateFeed(input: UpdateFeedRequest, options?: RpcOptions): UnaryCall<UpdateFeedRequest, UpdateFeedResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateFeedRequest, UpdateFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteFeed
     */
    deleteFeed(input: DeleteFeedRequest, options?: RpcOptions): UnaryCall<DeleteFeedRequest, DeleteFeedResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteFeedRequest, DeleteFeedResponse>("unary", this._transport, method, opt, input);
    }
}
