/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "wires/service.proto" (package "ttab.wires", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ttab.wires.GetAllFeedsRequest
 */
export interface GetAllFeedsRequest {
    /**
     * The page number to retrieve.
     * Defaults to 0 if not specified, representing the first page.
     *
     * @generated from protobuf field: int64 page = 1
     */
    page: bigint;
    /**
     * The number of items to include in each page of results.
     * Defaults to 10 if not specified.
     *
     * @generated from protobuf field: int64 page_size = 2
     */
    pageSize: bigint;
}
/**
 * @generated from protobuf message ttab.wires.GetAllFeedsResponse
 */
export interface GetAllFeedsResponse {
    /**
     * The current page number of the results being returned.
     * Reflects the "page" value from the request.
     *
     * @generated from protobuf field: int64 page = 1
     */
    page: bigint;
    /**
     * The page number of the next set of results, or -1 if there are no more pages.
     *
     * @generated from protobuf field: int64 next_page = 2
     */
    nextPage: bigint;
    /**
     * The list of feeds available on the current page sorted by title.
     *
     * @generated from protobuf field: repeated ttab.wires.Feed feeds = 3
     */
    feeds: Feed[];
}
/**
 * @generated from protobuf message ttab.wires.Feed
 */
export interface Feed {
    /**
     * UUIDv5 of the feed, created by using the url.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * The human-readable title of the feed.
     *
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * The URL from which the feed is sourced.
     *
     * @generated from protobuf field: string url = 3
     */
    url: string;
    /**
     * Feed type enum. "TYPE_ARTICLE" (default) and "TYPE_PRESSRELEASE".
     * Use "TYPE_ARTICLE" and "type_exceptions" field for feeds with mixed types.
     *
     * @generated from protobuf field: ttab.wires.FeedType type = 4
     */
    type: FeedType;
    /**
     * A list of exceptions for fine-grained type categorization of feed items.
     * Primarily used for feeds with mixed content types.
     *
     * @generated from protobuf field: repeated ttab.wires.ExceptionRule type_exceptions = 10
     */
    typeExceptions: ExceptionRule[];
    /**
     * Code representing the section of the feed.
     * Possible values: ["inr", "utr", "eko", "spt", "nojkul"].
     *
     * @generated from protobuf field: string section_code = 5
     */
    sectionCode: string;
    /**
     * Time interval (in seconds) specifying how frequently the feed should be refreshed/imported.
     *
     * @generated from protobuf field: int64 refresh_interval = 6
     */
    refreshInterval: bigint;
    /**
     * Language used in the feed. (BCP 47 standard)
     *
     * @generated from protobuf field: string language = 7
     */
    language: string;
    /**
     * The timestamp (ISO 8601 format) of the last time the feed was checked for updates.
     * This field is managed internally by the system and is not settable by clients in update requests.
     *
     * @generated from protobuf field: string last_checked = 8
     */
    lastChecked: string;
    /**
     * The timestamp (ISO 8601 format) of the most recent publication detected in the feed.
     * This field is managed internally by the system and is not settable by clients in update requests.
     *
     * @generated from protobuf field: string last_publication = 9
     */
    lastPublication: string;
}
/**
 * One or both fileds can be used in a rule.
 * If one of the fields in a rule matches a feed item, the exception is applied (logical OR).
 *
 * @generated from protobuf message ttab.wires.ExceptionRule
 */
export interface ExceptionRule {
    /**
     * A regex pattern to match against feed item titles.
     * Example: "^PRESS:" to match titles starting with "PRESS:".
     *
     * @generated from protobuf field: string title_pattern = 1
     */
    titlePattern: string;
    /**
     * A category to associate with feed items that match the title pattern.
     * Example: "Pressmeddelande" or "Pressrelease".
     *
     * @generated from protobuf field: string has_category = 2
     */
    hasCategory: string;
}
/**
 * @generated from protobuf message ttab.wires.UpdateFeedRequest
 */
export interface UpdateFeedRequest {
    /**
     * The feed object containing the updated data.
     * All fields must be set except intenally mangaged fields.
     *
     * @generated from protobuf field: ttab.wires.Feed feed = 1
     */
    feed?: Feed;
}
/**
 * @generated from protobuf message ttab.wires.UpdateFeedResponse
 */
export interface UpdateFeedResponse {
}
/**
 * @generated from protobuf message ttab.wires.DeleteFeedRequest
 */
export interface DeleteFeedRequest {
    /**
     * UUIDv5 of the feed, created by using the url.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
}
/**
 * @generated from protobuf message ttab.wires.DeleteFeedResponse
 */
export interface DeleteFeedResponse {
}
/**
 * @generated from protobuf enum ttab.wires.FeedType
 */
export enum FeedType {
    /**
     * @generated from protobuf enum value: TYPE_UNKNOWN = 0;
     */
    TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: TYPE_ARTICLE = 1;
     */
    TYPE_ARTICLE = 1,
    /**
     * @generated from protobuf enum value: TYPE_PRESSRELEASE = 2;
     */
    TYPE_PRESSRELEASE = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAllFeedsRequest$Type extends MessageType<GetAllFeedsRequest> {
    constructor() {
        super("ttab.wires.GetAllFeedsRequest", [
            { no: 1, name: "page", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "page_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetAllFeedsRequest>): GetAllFeedsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0n;
        message.pageSize = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetAllFeedsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllFeedsRequest): GetAllFeedsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 page */ 1:
                    message.page = reader.int64().toBigInt();
                    break;
                case /* int64 page_size */ 2:
                    message.pageSize = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllFeedsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 page = 1; */
        if (message.page !== 0n)
            writer.tag(1, WireType.Varint).int64(message.page);
        /* int64 page_size = 2; */
        if (message.pageSize !== 0n)
            writer.tag(2, WireType.Varint).int64(message.pageSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.GetAllFeedsRequest
 */
export const GetAllFeedsRequest = new GetAllFeedsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllFeedsResponse$Type extends MessageType<GetAllFeedsResponse> {
    constructor() {
        super("ttab.wires.GetAllFeedsResponse", [
            { no: 1, name: "page", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "next_page", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "feeds", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Feed }
        ]);
    }
    create(value?: PartialMessage<GetAllFeedsResponse>): GetAllFeedsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0n;
        message.nextPage = 0n;
        message.feeds = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllFeedsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllFeedsResponse): GetAllFeedsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 page */ 1:
                    message.page = reader.int64().toBigInt();
                    break;
                case /* int64 next_page */ 2:
                    message.nextPage = reader.int64().toBigInt();
                    break;
                case /* repeated ttab.wires.Feed feeds */ 3:
                    message.feeds.push(Feed.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllFeedsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 page = 1; */
        if (message.page !== 0n)
            writer.tag(1, WireType.Varint).int64(message.page);
        /* int64 next_page = 2; */
        if (message.nextPage !== 0n)
            writer.tag(2, WireType.Varint).int64(message.nextPage);
        /* repeated ttab.wires.Feed feeds = 3; */
        for (let i = 0; i < message.feeds.length; i++)
            Feed.internalBinaryWrite(message.feeds[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.GetAllFeedsResponse
 */
export const GetAllFeedsResponse = new GetAllFeedsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Feed$Type extends MessageType<Feed> {
    constructor() {
        super("ttab.wires.Feed", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "enum", T: () => ["ttab.wires.FeedType", FeedType] },
            { no: 10, name: "type_exceptions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ExceptionRule },
            { no: 5, name: "section_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "refresh_interval", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "language", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "last_checked", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "last_publication", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Feed>): Feed {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.title = "";
        message.url = "";
        message.type = 0;
        message.typeExceptions = [];
        message.sectionCode = "";
        message.refreshInterval = 0n;
        message.language = "";
        message.lastChecked = "";
        message.lastPublication = "";
        if (value !== undefined)
            reflectionMergePartial<Feed>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Feed): Feed {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string url */ 3:
                    message.url = reader.string();
                    break;
                case /* ttab.wires.FeedType type */ 4:
                    message.type = reader.int32();
                    break;
                case /* repeated ttab.wires.ExceptionRule type_exceptions */ 10:
                    message.typeExceptions.push(ExceptionRule.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string section_code */ 5:
                    message.sectionCode = reader.string();
                    break;
                case /* int64 refresh_interval */ 6:
                    message.refreshInterval = reader.int64().toBigInt();
                    break;
                case /* string language */ 7:
                    message.language = reader.string();
                    break;
                case /* string last_checked */ 8:
                    message.lastChecked = reader.string();
                    break;
                case /* string last_publication */ 9:
                    message.lastPublication = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Feed, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string url = 3; */
        if (message.url !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.url);
        /* ttab.wires.FeedType type = 4; */
        if (message.type !== 0)
            writer.tag(4, WireType.Varint).int32(message.type);
        /* string section_code = 5; */
        if (message.sectionCode !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.sectionCode);
        /* int64 refresh_interval = 6; */
        if (message.refreshInterval !== 0n)
            writer.tag(6, WireType.Varint).int64(message.refreshInterval);
        /* string language = 7; */
        if (message.language !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.language);
        /* string last_checked = 8; */
        if (message.lastChecked !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.lastChecked);
        /* string last_publication = 9; */
        if (message.lastPublication !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.lastPublication);
        /* repeated ttab.wires.ExceptionRule type_exceptions = 10; */
        for (let i = 0; i < message.typeExceptions.length; i++)
            ExceptionRule.internalBinaryWrite(message.typeExceptions[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.Feed
 */
export const Feed = new Feed$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExceptionRule$Type extends MessageType<ExceptionRule> {
    constructor() {
        super("ttab.wires.ExceptionRule", [
            { no: 1, name: "title_pattern", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "has_category", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ExceptionRule>): ExceptionRule {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.titlePattern = "";
        message.hasCategory = "";
        if (value !== undefined)
            reflectionMergePartial<ExceptionRule>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExceptionRule): ExceptionRule {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title_pattern */ 1:
                    message.titlePattern = reader.string();
                    break;
                case /* string has_category */ 2:
                    message.hasCategory = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExceptionRule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title_pattern = 1; */
        if (message.titlePattern !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.titlePattern);
        /* string has_category = 2; */
        if (message.hasCategory !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.hasCategory);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.ExceptionRule
 */
export const ExceptionRule = new ExceptionRule$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateFeedRequest$Type extends MessageType<UpdateFeedRequest> {
    constructor() {
        super("ttab.wires.UpdateFeedRequest", [
            { no: 1, name: "feed", kind: "message", T: () => Feed }
        ]);
    }
    create(value?: PartialMessage<UpdateFeedRequest>): UpdateFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateFeedRequest): UpdateFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ttab.wires.Feed feed */ 1:
                    message.feed = Feed.internalBinaryRead(reader, reader.uint32(), options, message.feed);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ttab.wires.Feed feed = 1; */
        if (message.feed)
            Feed.internalBinaryWrite(message.feed, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.UpdateFeedRequest
 */
export const UpdateFeedRequest = new UpdateFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateFeedResponse$Type extends MessageType<UpdateFeedResponse> {
    constructor() {
        super("ttab.wires.UpdateFeedResponse", []);
    }
    create(value?: PartialMessage<UpdateFeedResponse>): UpdateFeedResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateFeedResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateFeedResponse): UpdateFeedResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateFeedResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.UpdateFeedResponse
 */
export const UpdateFeedResponse = new UpdateFeedResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteFeedRequest$Type extends MessageType<DeleteFeedRequest> {
    constructor() {
        super("ttab.wires.DeleteFeedRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteFeedRequest>): DeleteFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteFeedRequest): DeleteFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.DeleteFeedRequest
 */
export const DeleteFeedRequest = new DeleteFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteFeedResponse$Type extends MessageType<DeleteFeedResponse> {
    constructor() {
        super("ttab.wires.DeleteFeedResponse", []);
    }
    create(value?: PartialMessage<DeleteFeedResponse>): DeleteFeedResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteFeedResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteFeedResponse): DeleteFeedResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteFeedResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.wires.DeleteFeedResponse
 */
export const DeleteFeedResponse = new DeleteFeedResponse$Type();
/**
 * @generated ServiceType for protobuf service ttab.wires.RssFeed
 */
export const RssFeed = new ServiceType("ttab.wires.RssFeed", [
    { name: "GetAllFeeds", options: {}, I: GetAllFeedsRequest, O: GetAllFeedsResponse },
    { name: "UpdateFeed", options: {}, I: UpdateFeedRequest, O: UpdateFeedResponse },
    { name: "DeleteFeed", options: {}, I: DeleteFeedRequest, O: DeleteFeedResponse }
]);
