/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "everysport/service.proto" (package "ttab.everysport", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Manage } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ManualImportResponse } from "./service";
import type { ManualImportRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ttab.everysport.Manage
 */
export interface IManageClient {
    /**
     * ManualImport re-imports calendar events based on a search query.
     *
     * @generated from protobuf rpc: ManualImport
     */
    manualImport(input: ManualImportRequest, options?: RpcOptions): UnaryCall<ManualImportRequest, ManualImportResponse>;
}
/**
 * @generated from protobuf service ttab.everysport.Manage
 */
export class ManageClient implements IManageClient, ServiceInfo {
    typeName = Manage.typeName;
    methods = Manage.methods;
    options = Manage.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * ManualImport re-imports calendar events based on a search query.
     *
     * @generated from protobuf rpc: ManualImport
     */
    manualImport(input: ManualImportRequest, options?: RpcOptions): UnaryCall<ManualImportRequest, ManualImportResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ManualImportRequest, ManualImportResponse>("unary", this._transport, method, opt, input);
    }
}
