/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "everysport/service.proto" (package "ttab.everysport", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ttab.everysport.ManualImportRequest
 */
export interface ManualImportRequest {
    /**
     * FromDate is the date from which to fetch events for import. Optional,
     * defaults to today.
     *
     * @generated from protobuf field: string from_date = 1
     */
    fromDate: string;
    /**
     * FromDate is the last date we should get events for. Optional.
     *
     * @generated from protobuf field: string to_date = 2
     */
    toDate: string;
    /**
     * Category only re-imports the events with the specific category.
     *
     * @generated from protobuf field: int64 category = 3
     */
    category: bigint;
    /**
     * Category only re-imports the events for the specific competition static ID.
     *
     * @generated from protobuf field: int64 competition = 4
     */
    competition: bigint;
    /**
     * Force overwrite of calendar entries.
     *
     * @generated from protobuf field: bool force = 5
     */
    force: boolean;
}
/**
 * @generated from protobuf message ttab.everysport.ManualImportResponse
 */
export interface ManualImportResponse {
    /**
     * QueuedImports is the total numer of events that were queued for import.
     *
     * @generated from protobuf field: int64 queued_imports = 1
     */
    queuedImports: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class ManualImportRequest$Type extends MessageType<ManualImportRequest> {
    constructor() {
        super("ttab.everysport.ManualImportRequest", [
            { no: 1, name: "from_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "to_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "category", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "competition", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "force", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ManualImportRequest>): ManualImportRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fromDate = "";
        message.toDate = "";
        message.category = 0n;
        message.competition = 0n;
        message.force = false;
        if (value !== undefined)
            reflectionMergePartial<ManualImportRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ManualImportRequest): ManualImportRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string from_date */ 1:
                    message.fromDate = reader.string();
                    break;
                case /* string to_date */ 2:
                    message.toDate = reader.string();
                    break;
                case /* int64 category */ 3:
                    message.category = reader.int64().toBigInt();
                    break;
                case /* int64 competition */ 4:
                    message.competition = reader.int64().toBigInt();
                    break;
                case /* bool force */ 5:
                    message.force = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ManualImportRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string from_date = 1; */
        if (message.fromDate !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fromDate);
        /* string to_date = 2; */
        if (message.toDate !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.toDate);
        /* int64 category = 3; */
        if (message.category !== 0n)
            writer.tag(3, WireType.Varint).int64(message.category);
        /* int64 competition = 4; */
        if (message.competition !== 0n)
            writer.tag(4, WireType.Varint).int64(message.competition);
        /* bool force = 5; */
        if (message.force !== false)
            writer.tag(5, WireType.Varint).bool(message.force);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.everysport.ManualImportRequest
 */
export const ManualImportRequest = new ManualImportRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ManualImportResponse$Type extends MessageType<ManualImportResponse> {
    constructor() {
        super("ttab.everysport.ManualImportResponse", [
            { no: 1, name: "queued_imports", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ManualImportResponse>): ManualImportResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.queuedImports = 0n;
        if (value !== undefined)
            reflectionMergePartial<ManualImportResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ManualImportResponse): ManualImportResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 queued_imports */ 1:
                    message.queuedImports = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ManualImportResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 queued_imports = 1; */
        if (message.queuedImports !== 0n)
            writer.tag(1, WireType.Varint).int64(message.queuedImports);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.everysport.ManualImportResponse
 */
export const ManualImportResponse = new ManualImportResponse$Type();
/**
 * @generated ServiceType for protobuf service ttab.everysport.Manage
 */
export const Manage = new ServiceType("ttab.everysport.Manage", [
    { name: "ManualImport", options: {}, I: ManualImportRequest, O: ManualImportResponse }
]);
