/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "reportingstream/service.proto" (package "ttab.reportingstream", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Document } from "../newsdoc/newsdoc";
/**
 * ACLEntry grants permissions to a subject or unit URI.
 *
 * @generated from protobuf message ttab.reportingstream.ACLEntry
 */
export interface ACLEntry {
    /**
     * URI of the grantee. An empty string means the calling user.
     *
     * @generated from protobuf field: string uri = 1
     */
    uri: string;
    /**
     * Permissions granted: "r" (read) and/or "w" (write).
     *
     * @generated from protobuf field: repeated string permissions = 2
     */
    permissions: string[];
}
/**
 * @generated from protobuf message ttab.reportingstream.CreateStreamRequest
 */
export interface CreateStreamRequest {
    /**
     * Title of the stream.
     *
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * Intro text for the stream.
     *
     * @generated from protobuf field: string intro_text = 2
     */
    introText: string;
    /**
     * Initial ACL entries. The creator is always granted read+write.
     *
     * @generated from protobuf field: repeated ttab.reportingstream.ACLEntry acl = 3
     */
    acl: ACLEntry[];
    /**
     * Whether the stream is visible in the public API.
     *
     * @generated from protobuf field: bool published = 4
     */
    published: boolean;
}
/**
 * @generated from protobuf message ttab.reportingstream.CreateStreamResponse
 */
export interface CreateStreamResponse {
    /**
     * UUID of the created stream.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
}
/**
 * @generated from protobuf message ttab.reportingstream.UpdateStreamMetadataRequest
 */
export interface UpdateStreamMetadataRequest {
    /**
     * UUID of the stream to update.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * New title for the stream.
     *
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * New intro text for the stream.
     *
     * @generated from protobuf field: string intro_text = 3
     */
    introText: string;
    /**
     * Whether the stream is visible in the public API.
     *
     * @generated from protobuf field: bool published = 4
     */
    published: boolean;
}
/**
 * @generated from protobuf message ttab.reportingstream.UpdateStreamMetadataResponse
 */
export interface UpdateStreamMetadataResponse {
}
/**
 * @generated from protobuf message ttab.reportingstream.CloseStreamRequest
 */
export interface CloseStreamRequest {
    /**
     * UUID of the stream to close.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
}
/**
 * @generated from protobuf message ttab.reportingstream.CloseStreamResponse
 */
export interface CloseStreamResponse {
}
/**
 * @generated from protobuf message ttab.reportingstream.SetStreamACLRequest
 */
export interface SetStreamACLRequest {
    /**
     * UUID of the stream.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * New ACL entries, replaces the existing ACL.
     *
     * @generated from protobuf field: repeated ttab.reportingstream.ACLEntry acl = 2
     */
    acl: ACLEntry[];
}
/**
 * @generated from protobuf message ttab.reportingstream.SetStreamACLResponse
 */
export interface SetStreamACLResponse {
}
/**
 * @generated from protobuf message ttab.reportingstream.CreatePostRequest
 */
export interface CreatePostRequest {
    /**
     * UUID of the stream to add the post to.
     *
     * @generated from protobuf field: string stream_uuid = 1
     */
    streamUuid: string;
    /**
     * NewsDoc document payload for the post.
     *
     * @generated from protobuf field: newsdoc.Document document = 2
     */
    document?: Document;
    /**
     * Timestamp to use for ordering the post.
     *
     * @generated from protobuf field: string post_timestamp = 3
     */
    postTimestamp: string;
    /**
     * Whether the post should be pinned to the top of the stream.
     *
     * @generated from protobuf field: bool pinned = 4
     */
    pinned: boolean;
}
/**
 * @generated from protobuf message ttab.reportingstream.CreatePostResponse
 */
export interface CreatePostResponse {
    /**
     * UUID of the created post.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
}
/**
 * @generated from protobuf message ttab.reportingstream.UpdatePostRequest
 */
export interface UpdatePostRequest {
    /**
     * UUID of the post to update.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * Updated NewsDoc document payload.
     *
     * @generated from protobuf field: newsdoc.Document document = 2
     */
    document?: Document;
    /**
     * Updated timestamp for ordering.
     *
     * @generated from protobuf field: string post_timestamp = 3
     */
    postTimestamp: string;
    /**
     * Updated pinned status.
     *
     * @generated from protobuf field: bool pinned = 4
     */
    pinned: boolean;
}
/**
 * @generated from protobuf message ttab.reportingstream.UpdatePostResponse
 */
export interface UpdatePostResponse {
}
/**
 * @generated from protobuf message ttab.reportingstream.DeletePostRequest
 */
export interface DeletePostRequest {
    /**
     * UUID of the post to delete.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
}
/**
 * @generated from protobuf message ttab.reportingstream.DeletePostResponse
 */
export interface DeletePostResponse {
}
/**
 * @generated from protobuf message ttab.reportingstream.GetStreamRequest
 */
export interface GetStreamRequest {
    /**
     * UUID of the stream.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
}
/**
 * @generated from protobuf message ttab.reportingstream.GetStreamResponse
 */
export interface GetStreamResponse {
    /**
     * Stream metadata.
     *
     * @generated from protobuf field: ttab.reportingstream.Stream stream = 1
     */
    stream?: Stream;
    /**
     * Access control list for the stream.
     *
     * @generated from protobuf field: repeated ttab.reportingstream.ACLEntry acl = 2
     */
    acl: ACLEntry[];
}
/**
 * @generated from protobuf message ttab.reportingstream.Stream
 */
export interface Stream {
    /**
     * UUID of the stream.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * Title of the stream.
     *
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * Intro text for the stream.
     *
     * @generated from protobuf field: string intro_text = 3
     */
    introText: string;
    /**
     * Whether the stream is closed.
     *
     * @generated from protobuf field: bool closed = 4
     */
    closed: boolean;
    /**
     * Creation timestamp (RFC 3339).
     *
     * @generated from protobuf field: string created_at = 5
     */
    createdAt: string;
    /**
     * Last update timestamp (RFC 3339).
     *
     * @generated from protobuf field: string updated_at = 6
     */
    updatedAt: string;
    /**
     * Whether the stream is visible in the public API.
     *
     * @generated from protobuf field: bool published = 7
     */
    published: boolean;
}
/**
 * @generated from protobuf message ttab.reportingstream.GetPostsRequest
 */
export interface GetPostsRequest {
    /**
     * UUID of the stream.
     *
     * @generated from protobuf field: string stream_uuid = 1
     */
    streamUuid: string;
    /**
     * Return the 10 posts before this event ID. Use 0 for the latest 10 posts.
     *
     * @generated from protobuf field: int64 before = 2
     */
    before: bigint;
}
/**
 * @generated from protobuf message ttab.reportingstream.GetPostsResponse
 */
export interface GetPostsResponse {
    /**
     * List of posts.
     *
     * @generated from protobuf field: repeated ttab.reportingstream.Post posts = 1
     */
    posts: Post[];
}
/**
 * @generated from protobuf message ttab.reportingstream.Post
 */
export interface Post {
    /**
     * UUID of the post.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * UUID of the stream this post belongs to.
     *
     * @generated from protobuf field: string stream_uuid = 2
     */
    streamUuid: string;
    /**
     * Document type (e.g. core/article, core/image).
     *
     * @generated from protobuf field: string type = 3
     */
    type: string;
    /**
     * NewsDoc document payload.
     *
     * @generated from protobuf field: newsdoc.Document document = 4
     */
    document?: Document;
    /**
     * Timestamp used for ordering.
     *
     * @generated from protobuf field: string post_timestamp = 5
     */
    postTimestamp: string;
    /**
     * Whether the post is pinned.
     *
     * @generated from protobuf field: bool pinned = 6
     */
    pinned: boolean;
    /**
     * Version number, incremented on each update.
     *
     * @generated from protobuf field: int64 version = 7
     */
    version: bigint;
    /**
     * Creation timestamp (RFC 3339).
     *
     * @generated from protobuf field: string created_at = 8
     */
    createdAt: string;
    /**
     * Last update timestamp (RFC 3339).
     *
     * @generated from protobuf field: string updated_at = 9
     */
    updatedAt: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ACLEntry$Type extends MessageType<ACLEntry> {
    constructor() {
        super("ttab.reportingstream.ACLEntry", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "permissions", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ACLEntry>): ACLEntry {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        message.permissions = [];
        if (value !== undefined)
            reflectionMergePartial<ACLEntry>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ACLEntry): ACLEntry {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* repeated string permissions */ 2:
                    message.permissions.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ACLEntry, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* repeated string permissions = 2; */
        for (let i = 0; i < message.permissions.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.permissions[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.ACLEntry
 */
export const ACLEntry = new ACLEntry$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateStreamRequest$Type extends MessageType<CreateStreamRequest> {
    constructor() {
        super("ttab.reportingstream.CreateStreamRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "intro_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "acl", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ACLEntry },
            { no: 4, name: "published", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreateStreamRequest>): CreateStreamRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.introText = "";
        message.acl = [];
        message.published = false;
        if (value !== undefined)
            reflectionMergePartial<CreateStreamRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateStreamRequest): CreateStreamRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string intro_text */ 2:
                    message.introText = reader.string();
                    break;
                case /* repeated ttab.reportingstream.ACLEntry acl */ 3:
                    message.acl.push(ACLEntry.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool published */ 4:
                    message.published = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateStreamRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string intro_text = 2; */
        if (message.introText !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.introText);
        /* repeated ttab.reportingstream.ACLEntry acl = 3; */
        for (let i = 0; i < message.acl.length; i++)
            ACLEntry.internalBinaryWrite(message.acl[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bool published = 4; */
        if (message.published !== false)
            writer.tag(4, WireType.Varint).bool(message.published);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.CreateStreamRequest
 */
export const CreateStreamRequest = new CreateStreamRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateStreamResponse$Type extends MessageType<CreateStreamResponse> {
    constructor() {
        super("ttab.reportingstream.CreateStreamResponse", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateStreamResponse>): CreateStreamResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        if (value !== undefined)
            reflectionMergePartial<CreateStreamResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateStreamResponse): CreateStreamResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateStreamResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.CreateStreamResponse
 */
export const CreateStreamResponse = new CreateStreamResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateStreamMetadataRequest$Type extends MessageType<UpdateStreamMetadataRequest> {
    constructor() {
        super("ttab.reportingstream.UpdateStreamMetadataRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "intro_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "published", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateStreamMetadataRequest>): UpdateStreamMetadataRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.title = "";
        message.introText = "";
        message.published = false;
        if (value !== undefined)
            reflectionMergePartial<UpdateStreamMetadataRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateStreamMetadataRequest): UpdateStreamMetadataRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string intro_text */ 3:
                    message.introText = reader.string();
                    break;
                case /* bool published */ 4:
                    message.published = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateStreamMetadataRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string intro_text = 3; */
        if (message.introText !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.introText);
        /* bool published = 4; */
        if (message.published !== false)
            writer.tag(4, WireType.Varint).bool(message.published);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.UpdateStreamMetadataRequest
 */
export const UpdateStreamMetadataRequest = new UpdateStreamMetadataRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateStreamMetadataResponse$Type extends MessageType<UpdateStreamMetadataResponse> {
    constructor() {
        super("ttab.reportingstream.UpdateStreamMetadataResponse", []);
    }
    create(value?: PartialMessage<UpdateStreamMetadataResponse>): UpdateStreamMetadataResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateStreamMetadataResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateStreamMetadataResponse): UpdateStreamMetadataResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateStreamMetadataResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.UpdateStreamMetadataResponse
 */
export const UpdateStreamMetadataResponse = new UpdateStreamMetadataResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CloseStreamRequest$Type extends MessageType<CloseStreamRequest> {
    constructor() {
        super("ttab.reportingstream.CloseStreamRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CloseStreamRequest>): CloseStreamRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        if (value !== undefined)
            reflectionMergePartial<CloseStreamRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CloseStreamRequest): CloseStreamRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CloseStreamRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.CloseStreamRequest
 */
export const CloseStreamRequest = new CloseStreamRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CloseStreamResponse$Type extends MessageType<CloseStreamResponse> {
    constructor() {
        super("ttab.reportingstream.CloseStreamResponse", []);
    }
    create(value?: PartialMessage<CloseStreamResponse>): CloseStreamResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CloseStreamResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CloseStreamResponse): CloseStreamResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CloseStreamResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.CloseStreamResponse
 */
export const CloseStreamResponse = new CloseStreamResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetStreamACLRequest$Type extends MessageType<SetStreamACLRequest> {
    constructor() {
        super("ttab.reportingstream.SetStreamACLRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "acl", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ACLEntry }
        ]);
    }
    create(value?: PartialMessage<SetStreamACLRequest>): SetStreamACLRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.acl = [];
        if (value !== undefined)
            reflectionMergePartial<SetStreamACLRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetStreamACLRequest): SetStreamACLRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* repeated ttab.reportingstream.ACLEntry acl */ 2:
                    message.acl.push(ACLEntry.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetStreamACLRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* repeated ttab.reportingstream.ACLEntry acl = 2; */
        for (let i = 0; i < message.acl.length; i++)
            ACLEntry.internalBinaryWrite(message.acl[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.SetStreamACLRequest
 */
export const SetStreamACLRequest = new SetStreamACLRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetStreamACLResponse$Type extends MessageType<SetStreamACLResponse> {
    constructor() {
        super("ttab.reportingstream.SetStreamACLResponse", []);
    }
    create(value?: PartialMessage<SetStreamACLResponse>): SetStreamACLResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SetStreamACLResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetStreamACLResponse): SetStreamACLResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetStreamACLResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.SetStreamACLResponse
 */
export const SetStreamACLResponse = new SetStreamACLResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePostRequest$Type extends MessageType<CreatePostRequest> {
    constructor() {
        super("ttab.reportingstream.CreatePostRequest", [
            { no: 1, name: "stream_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "document", kind: "message", T: () => Document },
            { no: 3, name: "post_timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "pinned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePostRequest>): CreatePostRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.streamUuid = "";
        message.postTimestamp = "";
        message.pinned = false;
        if (value !== undefined)
            reflectionMergePartial<CreatePostRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePostRequest): CreatePostRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_uuid */ 1:
                    message.streamUuid = reader.string();
                    break;
                case /* newsdoc.Document document */ 2:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                case /* string post_timestamp */ 3:
                    message.postTimestamp = reader.string();
                    break;
                case /* bool pinned */ 4:
                    message.pinned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePostRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_uuid = 1; */
        if (message.streamUuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamUuid);
        /* newsdoc.Document document = 2; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string post_timestamp = 3; */
        if (message.postTimestamp !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.postTimestamp);
        /* bool pinned = 4; */
        if (message.pinned !== false)
            writer.tag(4, WireType.Varint).bool(message.pinned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.CreatePostRequest
 */
export const CreatePostRequest = new CreatePostRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePostResponse$Type extends MessageType<CreatePostResponse> {
    constructor() {
        super("ttab.reportingstream.CreatePostResponse", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePostResponse>): CreatePostResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        if (value !== undefined)
            reflectionMergePartial<CreatePostResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePostResponse): CreatePostResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePostResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.CreatePostResponse
 */
export const CreatePostResponse = new CreatePostResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePostRequest$Type extends MessageType<UpdatePostRequest> {
    constructor() {
        super("ttab.reportingstream.UpdatePostRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "document", kind: "message", T: () => Document },
            { no: 3, name: "post_timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "pinned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UpdatePostRequest>): UpdatePostRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.postTimestamp = "";
        message.pinned = false;
        if (value !== undefined)
            reflectionMergePartial<UpdatePostRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePostRequest): UpdatePostRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* newsdoc.Document document */ 2:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                case /* string post_timestamp */ 3:
                    message.postTimestamp = reader.string();
                    break;
                case /* bool pinned */ 4:
                    message.pinned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePostRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* newsdoc.Document document = 2; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string post_timestamp = 3; */
        if (message.postTimestamp !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.postTimestamp);
        /* bool pinned = 4; */
        if (message.pinned !== false)
            writer.tag(4, WireType.Varint).bool(message.pinned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.UpdatePostRequest
 */
export const UpdatePostRequest = new UpdatePostRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePostResponse$Type extends MessageType<UpdatePostResponse> {
    constructor() {
        super("ttab.reportingstream.UpdatePostResponse", []);
    }
    create(value?: PartialMessage<UpdatePostResponse>): UpdatePostResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdatePostResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePostResponse): UpdatePostResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePostResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.UpdatePostResponse
 */
export const UpdatePostResponse = new UpdatePostResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePostRequest$Type extends MessageType<DeletePostRequest> {
    constructor() {
        super("ttab.reportingstream.DeletePostRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePostRequest>): DeletePostRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        if (value !== undefined)
            reflectionMergePartial<DeletePostRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePostRequest): DeletePostRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePostRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.DeletePostRequest
 */
export const DeletePostRequest = new DeletePostRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePostResponse$Type extends MessageType<DeletePostResponse> {
    constructor() {
        super("ttab.reportingstream.DeletePostResponse", []);
    }
    create(value?: PartialMessage<DeletePostResponse>): DeletePostResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeletePostResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePostResponse): DeletePostResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePostResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.DeletePostResponse
 */
export const DeletePostResponse = new DeletePostResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetStreamRequest$Type extends MessageType<GetStreamRequest> {
    constructor() {
        super("ttab.reportingstream.GetStreamRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetStreamRequest>): GetStreamRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        if (value !== undefined)
            reflectionMergePartial<GetStreamRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetStreamRequest): GetStreamRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetStreamRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.GetStreamRequest
 */
export const GetStreamRequest = new GetStreamRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetStreamResponse$Type extends MessageType<GetStreamResponse> {
    constructor() {
        super("ttab.reportingstream.GetStreamResponse", [
            { no: 1, name: "stream", kind: "message", T: () => Stream },
            { no: 2, name: "acl", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ACLEntry }
        ]);
    }
    create(value?: PartialMessage<GetStreamResponse>): GetStreamResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.acl = [];
        if (value !== undefined)
            reflectionMergePartial<GetStreamResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetStreamResponse): GetStreamResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ttab.reportingstream.Stream stream */ 1:
                    message.stream = Stream.internalBinaryRead(reader, reader.uint32(), options, message.stream);
                    break;
                case /* repeated ttab.reportingstream.ACLEntry acl */ 2:
                    message.acl.push(ACLEntry.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetStreamResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ttab.reportingstream.Stream stream = 1; */
        if (message.stream)
            Stream.internalBinaryWrite(message.stream, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated ttab.reportingstream.ACLEntry acl = 2; */
        for (let i = 0; i < message.acl.length; i++)
            ACLEntry.internalBinaryWrite(message.acl[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.GetStreamResponse
 */
export const GetStreamResponse = new GetStreamResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Stream$Type extends MessageType<Stream> {
    constructor() {
        super("ttab.reportingstream.Stream", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "intro_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "closed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "published", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Stream>): Stream {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.title = "";
        message.introText = "";
        message.closed = false;
        message.createdAt = "";
        message.updatedAt = "";
        message.published = false;
        if (value !== undefined)
            reflectionMergePartial<Stream>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Stream): Stream {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string intro_text */ 3:
                    message.introText = reader.string();
                    break;
                case /* bool closed */ 4:
                    message.closed = reader.bool();
                    break;
                case /* string created_at */ 5:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 6:
                    message.updatedAt = reader.string();
                    break;
                case /* bool published */ 7:
                    message.published = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Stream, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string intro_text = 3; */
        if (message.introText !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.introText);
        /* bool closed = 4; */
        if (message.closed !== false)
            writer.tag(4, WireType.Varint).bool(message.closed);
        /* string created_at = 5; */
        if (message.createdAt !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 6; */
        if (message.updatedAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.updatedAt);
        /* bool published = 7; */
        if (message.published !== false)
            writer.tag(7, WireType.Varint).bool(message.published);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.Stream
 */
export const Stream = new Stream$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostsRequest$Type extends MessageType<GetPostsRequest> {
    constructor() {
        super("ttab.reportingstream.GetPostsRequest", [
            { no: 1, name: "stream_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "before", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetPostsRequest>): GetPostsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.streamUuid = "";
        message.before = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetPostsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostsRequest): GetPostsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_uuid */ 1:
                    message.streamUuid = reader.string();
                    break;
                case /* int64 before */ 2:
                    message.before = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_uuid = 1; */
        if (message.streamUuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamUuid);
        /* int64 before = 2; */
        if (message.before !== 0n)
            writer.tag(2, WireType.Varint).int64(message.before);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.GetPostsRequest
 */
export const GetPostsRequest = new GetPostsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostsResponse$Type extends MessageType<GetPostsResponse> {
    constructor() {
        super("ttab.reportingstream.GetPostsResponse", [
            { no: 1, name: "posts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Post }
        ]);
    }
    create(value?: PartialMessage<GetPostsResponse>): GetPostsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posts = [];
        if (value !== undefined)
            reflectionMergePartial<GetPostsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostsResponse): GetPostsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ttab.reportingstream.Post posts */ 1:
                    message.posts.push(Post.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ttab.reportingstream.Post posts = 1; */
        for (let i = 0; i < message.posts.length; i++)
            Post.internalBinaryWrite(message.posts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.GetPostsResponse
 */
export const GetPostsResponse = new GetPostsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Post$Type extends MessageType<Post> {
    constructor() {
        super("ttab.reportingstream.Post", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "stream_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "document", kind: "message", T: () => Document },
            { no: 5, name: "post_timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "pinned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "version", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Post>): Post {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.streamUuid = "";
        message.type = "";
        message.postTimestamp = "";
        message.pinned = false;
        message.version = 0n;
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<Post>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Post): Post {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string stream_uuid */ 2:
                    message.streamUuid = reader.string();
                    break;
                case /* string type */ 3:
                    message.type = reader.string();
                    break;
                case /* newsdoc.Document document */ 4:
                    message.document = Document.internalBinaryRead(reader, reader.uint32(), options, message.document);
                    break;
                case /* string post_timestamp */ 5:
                    message.postTimestamp = reader.string();
                    break;
                case /* bool pinned */ 6:
                    message.pinned = reader.bool();
                    break;
                case /* int64 version */ 7:
                    message.version = reader.int64().toBigInt();
                    break;
                case /* string created_at */ 8:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 9:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Post, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string stream_uuid = 2; */
        if (message.streamUuid !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.streamUuid);
        /* string type = 3; */
        if (message.type !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.type);
        /* newsdoc.Document document = 4; */
        if (message.document)
            Document.internalBinaryWrite(message.document, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string post_timestamp = 5; */
        if (message.postTimestamp !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.postTimestamp);
        /* bool pinned = 6; */
        if (message.pinned !== false)
            writer.tag(6, WireType.Varint).bool(message.pinned);
        /* int64 version = 7; */
        if (message.version !== 0n)
            writer.tag(7, WireType.Varint).int64(message.version);
        /* string created_at = 8; */
        if (message.createdAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 9; */
        if (message.updatedAt !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ttab.reportingstream.Post
 */
export const Post = new Post$Type();
/**
 * @generated ServiceType for protobuf service ttab.reportingstream.Streams
 */
export const Streams = new ServiceType("ttab.reportingstream.Streams", [
    { name: "CreateStream", options: {}, I: CreateStreamRequest, O: CreateStreamResponse },
    { name: "UpdateStreamMetadata", options: {}, I: UpdateStreamMetadataRequest, O: UpdateStreamMetadataResponse },
    { name: "CloseStream", options: {}, I: CloseStreamRequest, O: CloseStreamResponse },
    { name: "SetStreamACL", options: {}, I: SetStreamACLRequest, O: SetStreamACLResponse },
    { name: "CreatePost", options: {}, I: CreatePostRequest, O: CreatePostResponse },
    { name: "UpdatePost", options: {}, I: UpdatePostRequest, O: UpdatePostResponse },
    { name: "DeletePost", options: {}, I: DeletePostRequest, O: DeletePostResponse },
    { name: "GetStream", options: {}, I: GetStreamRequest, O: GetStreamResponse },
    { name: "GetPosts", options: {}, I: GetPostsRequest, O: GetPostsResponse }
]);
