/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "reportingstream/service.proto" (package "ttab.reportingstream", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Streams } from "./service";
import type { GetPostsResponse } from "./service";
import type { GetPostsRequest } from "./service";
import type { GetStreamResponse } from "./service";
import type { GetStreamRequest } from "./service";
import type { DeletePostResponse } from "./service";
import type { DeletePostRequest } from "./service";
import type { UpdatePostResponse } from "./service";
import type { UpdatePostRequest } from "./service";
import type { CreatePostResponse } from "./service";
import type { CreatePostRequest } from "./service";
import type { SetStreamACLResponse } from "./service";
import type { SetStreamACLRequest } from "./service";
import type { CloseStreamResponse } from "./service";
import type { CloseStreamRequest } from "./service";
import type { UpdateStreamMetadataResponse } from "./service";
import type { UpdateStreamMetadataRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateStreamResponse } from "./service";
import type { CreateStreamRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Streams is the editorial management service for reporting streams.
 *
 * @generated from protobuf service ttab.reportingstream.Streams
 */
export interface IStreamsClient {
    /**
     * CreateStream creates a new reporting stream.
     *
     * @generated from protobuf rpc: CreateStream
     */
    createStream(input: CreateStreamRequest, options?: RpcOptions): UnaryCall<CreateStreamRequest, CreateStreamResponse>;
    /**
     * UpdateStreamMetadata updates a stream's title, intro text, and published
     * status.
     *
     * @generated from protobuf rpc: UpdateStreamMetadata
     */
    updateStreamMetadata(input: UpdateStreamMetadataRequest, options?: RpcOptions): UnaryCall<UpdateStreamMetadataRequest, UpdateStreamMetadataResponse>;
    /**
     * CloseStream closes a stream, stopping further updates.
     *
     * @generated from protobuf rpc: CloseStream
     */
    closeStream(input: CloseStreamRequest, options?: RpcOptions): UnaryCall<CloseStreamRequest, CloseStreamResponse>;
    /**
     * SetStreamACL replaces the ACL for a stream.
     *
     * @generated from protobuf rpc: SetStreamACL
     */
    setStreamACL(input: SetStreamACLRequest, options?: RpcOptions): UnaryCall<SetStreamACLRequest, SetStreamACLResponse>;
    /**
     * CreatePost adds a post with a NewsDoc payload to a stream.
     *
     * @generated from protobuf rpc: CreatePost
     */
    createPost(input: CreatePostRequest, options?: RpcOptions): UnaryCall<CreatePostRequest, CreatePostResponse>;
    /**
     * UpdatePost updates a post's content, timestamp, or pinned status.
     *
     * @generated from protobuf rpc: UpdatePost
     */
    updatePost(input: UpdatePostRequest, options?: RpcOptions): UnaryCall<UpdatePostRequest, UpdatePostResponse>;
    /**
     * DeletePost soft-deletes a post from a stream.
     *
     * @generated from protobuf rpc: DeletePost
     */
    deletePost(input: DeletePostRequest, options?: RpcOptions): UnaryCall<DeletePostRequest, DeletePostResponse>;
    /**
     * GetStream returns stream metadata and ACL.
     *
     * @generated from protobuf rpc: GetStream
     */
    getStream(input: GetStreamRequest, options?: RpcOptions): UnaryCall<GetStreamRequest, GetStreamResponse>;
    /**
     * GetPosts returns the 10 latest posts, or the 10 posts before a given
     * event ID.
     *
     * @generated from protobuf rpc: GetPosts
     */
    getPosts(input: GetPostsRequest, options?: RpcOptions): UnaryCall<GetPostsRequest, GetPostsResponse>;
}
/**
 * Streams is the editorial management service for reporting streams.
 *
 * @generated from protobuf service ttab.reportingstream.Streams
 */
export class StreamsClient implements IStreamsClient, ServiceInfo {
    typeName = Streams.typeName;
    methods = Streams.methods;
    options = Streams.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * CreateStream creates a new reporting stream.
     *
     * @generated from protobuf rpc: CreateStream
     */
    createStream(input: CreateStreamRequest, options?: RpcOptions): UnaryCall<CreateStreamRequest, CreateStreamResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateStreamRequest, CreateStreamResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateStreamMetadata updates a stream's title, intro text, and published
     * status.
     *
     * @generated from protobuf rpc: UpdateStreamMetadata
     */
    updateStreamMetadata(input: UpdateStreamMetadataRequest, options?: RpcOptions): UnaryCall<UpdateStreamMetadataRequest, UpdateStreamMetadataResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateStreamMetadataRequest, UpdateStreamMetadataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * CloseStream closes a stream, stopping further updates.
     *
     * @generated from protobuf rpc: CloseStream
     */
    closeStream(input: CloseStreamRequest, options?: RpcOptions): UnaryCall<CloseStreamRequest, CloseStreamResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CloseStreamRequest, CloseStreamResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * SetStreamACL replaces the ACL for a stream.
     *
     * @generated from protobuf rpc: SetStreamACL
     */
    setStreamACL(input: SetStreamACLRequest, options?: RpcOptions): UnaryCall<SetStreamACLRequest, SetStreamACLResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetStreamACLRequest, SetStreamACLResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * CreatePost adds a post with a NewsDoc payload to a stream.
     *
     * @generated from protobuf rpc: CreatePost
     */
    createPost(input: CreatePostRequest, options?: RpcOptions): UnaryCall<CreatePostRequest, CreatePostResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePostRequest, CreatePostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdatePost updates a post's content, timestamp, or pinned status.
     *
     * @generated from protobuf rpc: UpdatePost
     */
    updatePost(input: UpdatePostRequest, options?: RpcOptions): UnaryCall<UpdatePostRequest, UpdatePostResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePostRequest, UpdatePostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * DeletePost soft-deletes a post from a stream.
     *
     * @generated from protobuf rpc: DeletePost
     */
    deletePost(input: DeletePostRequest, options?: RpcOptions): UnaryCall<DeletePostRequest, DeletePostResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePostRequest, DeletePostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetStream returns stream metadata and ACL.
     *
     * @generated from protobuf rpc: GetStream
     */
    getStream(input: GetStreamRequest, options?: RpcOptions): UnaryCall<GetStreamRequest, GetStreamResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetStreamRequest, GetStreamResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetPosts returns the 10 latest posts, or the 10 posts before a given
     * event ID.
     *
     * @generated from protobuf rpc: GetPosts
     */
    getPosts(input: GetPostsRequest, options?: RpcOptions): UnaryCall<GetPostsRequest, GetPostsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostsRequest, GetPostsResponse>("unary", this._transport, method, opt, input);
    }
}
