/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "hub/service.proto" (package "ttab.hub", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Hub } from "./service";
import type { ListGitHubOrgsResponse } from "./service";
import type { ListGitHubOrgsRequest } from "./service";
import type { RemoveGitHubOrgResponse } from "./service";
import type { RemoveGitHubOrgRequest } from "./service";
import type { AddGitHubOrgResponse } from "./service";
import type { AddGitHubOrgRequest } from "./service";
import type { SetArtifactVisibilityResponse } from "./service";
import type { SetArtifactVisibilityRequest } from "./service";
import type { ListArtifactPermissionsResponse } from "./service";
import type { ListArtifactPermissionsRequest } from "./service";
import type { RemoveAllowedDeployKeyResponse } from "./service";
import type { RemoveAllowedDeployKeyRequest } from "./service";
import type { AddAllowedDeployKeyResponse } from "./service";
import type { AddAllowedDeployKeyRequest } from "./service";
import type { RemoveAllowedSANResponse } from "./service";
import type { RemoveAllowedSANRequest } from "./service";
import type { AddAllowedSANResponse } from "./service";
import type { AddAllowedSANRequest } from "./service";
import type { RevokeDeployKeyResponse } from "./service";
import type { RevokeDeployKeyRequest } from "./service";
import type { ApproveDeployKeyResponse } from "./service";
import type { ApproveDeployKeyRequest } from "./service";
import type { ListDeployKeysResponse } from "./service";
import type { ListDeployKeysRequest } from "./service";
import type { RegisterDeployKeyResponse } from "./service";
import type { RegisterDeployKeyRequest } from "./service";
import type { RevokeVersionResponse } from "./service";
import type { RevokeVersionRequest } from "./service";
import type { PublishVersionResponse } from "./service";
import type { PublishVersionRequest } from "./service";
import type { GetArtifactAssetResponse } from "./service";
import type { GetArtifactAssetRequest } from "./service";
import type { GetArtifactVersionResponse } from "./service";
import type { GetArtifactVersionRequest } from "./service";
import type { GetArtifactResponse } from "./service";
import type { GetArtifactRequest } from "./service";
import type { ListArtifactsResponse } from "./service";
import type { ListArtifactsRequest } from "./service";
import type { ApproveOrganisationResponse } from "./service";
import type { ApproveOrganisationRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListOrganisationsResponse } from "./service";
import type { ListOrganisationsRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Hub provides the API for managing schemas and plugins in the
 * Elephant Hub registry.
 *
 * --- Organisation management ---
 *
 * @generated from protobuf service ttab.hub.Hub
 */
export interface IHubClient {
    /**
     * ListOrganisations returns all registered organisations.
     *
     * @generated from protobuf rpc: ListOrganisations
     */
    listOrganisations(input: ListOrganisationsRequest, options?: RpcOptions): UnaryCall<ListOrganisationsRequest, ListOrganisationsResponse>;
    /**
     * ApproveOrganisation approves an organisation, allowing its members to log in.
     *
     * @generated from protobuf rpc: ApproveOrganisation
     */
    approveOrganisation(input: ApproveOrganisationRequest, options?: RpcOptions): UnaryCall<ApproveOrganisationRequest, ApproveOrganisationResponse>;
    // --- Artifact browsing ---

    /**
     * ListArtifacts returns artifacts, optionally filtered by kind.
     *
     * @generated from protobuf rpc: ListArtifacts
     */
    listArtifacts(input: ListArtifactsRequest, options?: RpcOptions): UnaryCall<ListArtifactsRequest, ListArtifactsResponse>;
    /**
     * GetArtifact returns metadata for a specific artifact.
     *
     * @generated from protobuf rpc: GetArtifact
     */
    getArtifact(input: GetArtifactRequest, options?: RpcOptions): UnaryCall<GetArtifactRequest, GetArtifactResponse>;
    /**
     * GetArtifactVersion returns a specific version of an artifact including its manifest.
     *
     * @generated from protobuf rpc: GetArtifactVersion
     */
    getArtifactVersion(input: GetArtifactVersionRequest, options?: RpcOptions): UnaryCall<GetArtifactVersionRequest, GetArtifactVersionResponse>;
    /**
     * GetArtifactAsset returns the contents of a specific asset file.
     *
     * @generated from protobuf rpc: GetArtifactAsset
     */
    getArtifactAsset(input: GetArtifactAssetRequest, options?: RpcOptions): UnaryCall<GetArtifactAssetRequest, GetArtifactAssetResponse>;
    // --- Publishing ---

    /**
     * PublishVersion publishes a new version of a schema or plugin.
     *
     * @generated from protobuf rpc: PublishVersion
     */
    publishVersion(input: PublishVersionRequest, options?: RpcOptions): UnaryCall<PublishVersionRequest, PublishVersionResponse>;
    /**
     * RevokeVersion marks a published version as revoked.
     *
     * @generated from protobuf rpc: RevokeVersion
     */
    revokeVersion(input: RevokeVersionRequest, options?: RpcOptions): UnaryCall<RevokeVersionRequest, RevokeVersionResponse>;
    // --- Deploy key management ---

    /**
     * RegisterDeployKey registers a new deploy key for the authenticated user.
     *
     * @generated from protobuf rpc: RegisterDeployKey
     */
    registerDeployKey(input: RegisterDeployKeyRequest, options?: RpcOptions): UnaryCall<RegisterDeployKeyRequest, RegisterDeployKeyResponse>;
    /**
     * ListDeployKeys lists registered deploy keys.
     *
     * @generated from protobuf rpc: ListDeployKeys
     */
    listDeployKeys(input: ListDeployKeysRequest, options?: RpcOptions): UnaryCall<ListDeployKeysRequest, ListDeployKeysResponse>;
    /**
     * ApproveDeployKey approves a deploy key for publishing.
     *
     * @generated from protobuf rpc: ApproveDeployKey
     */
    approveDeployKey(input: ApproveDeployKeyRequest, options?: RpcOptions): UnaryCall<ApproveDeployKeyRequest, ApproveDeployKeyResponse>;
    /**
     * RevokeDeployKey revokes a deploy key.
     *
     * @generated from protobuf rpc: RevokeDeployKey
     */
    revokeDeployKey(input: RevokeDeployKeyRequest, options?: RpcOptions): UnaryCall<RevokeDeployKeyRequest, RevokeDeployKeyResponse>;
    // --- Artifact permissions ---

    /**
     * AddAllowedSAN adds a cosign SAN pattern allowed to publish an artifact.
     *
     * @generated from protobuf rpc: AddAllowedSAN
     */
    addAllowedSAN(input: AddAllowedSANRequest, options?: RpcOptions): UnaryCall<AddAllowedSANRequest, AddAllowedSANResponse>;
    /**
     * RemoveAllowedSAN removes an allowed SAN pattern from an artifact.
     *
     * @generated from protobuf rpc: RemoveAllowedSAN
     */
    removeAllowedSAN(input: RemoveAllowedSANRequest, options?: RpcOptions): UnaryCall<RemoveAllowedSANRequest, RemoveAllowedSANResponse>;
    /**
     * AddAllowedDeployKey adds a deploy key allowed to publish an artifact.
     *
     * @generated from protobuf rpc: AddAllowedDeployKey
     */
    addAllowedDeployKey(input: AddAllowedDeployKeyRequest, options?: RpcOptions): UnaryCall<AddAllowedDeployKeyRequest, AddAllowedDeployKeyResponse>;
    /**
     * RemoveAllowedDeployKey removes a deploy key from an artifact's allow list.
     *
     * @generated from protobuf rpc: RemoveAllowedDeployKey
     */
    removeAllowedDeployKey(input: RemoveAllowedDeployKeyRequest, options?: RpcOptions): UnaryCall<RemoveAllowedDeployKeyRequest, RemoveAllowedDeployKeyResponse>;
    /**
     * ListArtifactPermissions lists the SANs and deploy keys allowed for an artifact.
     *
     * @generated from protobuf rpc: ListArtifactPermissions
     */
    listArtifactPermissions(input: ListArtifactPermissionsRequest, options?: RpcOptions): UnaryCall<ListArtifactPermissionsRequest, ListArtifactPermissionsResponse>;
    // --- Visibility ---

    /**
     * SetArtifactVisibility sets whether an artifact is publicly visible.
     *
     * @generated from protobuf rpc: SetArtifactVisibility
     */
    setArtifactVisibility(input: SetArtifactVisibilityRequest, options?: RpcOptions): UnaryCall<SetArtifactVisibilityRequest, SetArtifactVisibilityResponse>;
    // --- GitHub organisation management ---

    /**
     * AddGitHubOrg links a GitHub organisation to a hub organisation.
     *
     * @generated from protobuf rpc: AddGitHubOrg
     */
    addGitHubOrg(input: AddGitHubOrgRequest, options?: RpcOptions): UnaryCall<AddGitHubOrgRequest, AddGitHubOrgResponse>;
    /**
     * RemoveGitHubOrg removes a GitHub organisation mapping.
     *
     * @generated from protobuf rpc: RemoveGitHubOrg
     */
    removeGitHubOrg(input: RemoveGitHubOrgRequest, options?: RpcOptions): UnaryCall<RemoveGitHubOrgRequest, RemoveGitHubOrgResponse>;
    /**
     * ListGitHubOrgs lists all GitHub organisation mappings.
     *
     * @generated from protobuf rpc: ListGitHubOrgs
     */
    listGitHubOrgs(input: ListGitHubOrgsRequest, options?: RpcOptions): UnaryCall<ListGitHubOrgsRequest, ListGitHubOrgsResponse>;
}
/**
 * Hub provides the API for managing schemas and plugins in the
 * Elephant Hub registry.
 *
 * --- Organisation management ---
 *
 * @generated from protobuf service ttab.hub.Hub
 */
export class HubClient implements IHubClient, ServiceInfo {
    typeName = Hub.typeName;
    methods = Hub.methods;
    options = Hub.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * ListOrganisations returns all registered organisations.
     *
     * @generated from protobuf rpc: ListOrganisations
     */
    listOrganisations(input: ListOrganisationsRequest, options?: RpcOptions): UnaryCall<ListOrganisationsRequest, ListOrganisationsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListOrganisationsRequest, ListOrganisationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ApproveOrganisation approves an organisation, allowing its members to log in.
     *
     * @generated from protobuf rpc: ApproveOrganisation
     */
    approveOrganisation(input: ApproveOrganisationRequest, options?: RpcOptions): UnaryCall<ApproveOrganisationRequest, ApproveOrganisationResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ApproveOrganisationRequest, ApproveOrganisationResponse>("unary", this._transport, method, opt, input);
    }
    // --- Artifact browsing ---

    /**
     * ListArtifacts returns artifacts, optionally filtered by kind.
     *
     * @generated from protobuf rpc: ListArtifacts
     */
    listArtifacts(input: ListArtifactsRequest, options?: RpcOptions): UnaryCall<ListArtifactsRequest, ListArtifactsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListArtifactsRequest, ListArtifactsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetArtifact returns metadata for a specific artifact.
     *
     * @generated from protobuf rpc: GetArtifact
     */
    getArtifact(input: GetArtifactRequest, options?: RpcOptions): UnaryCall<GetArtifactRequest, GetArtifactResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetArtifactRequest, GetArtifactResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetArtifactVersion returns a specific version of an artifact including its manifest.
     *
     * @generated from protobuf rpc: GetArtifactVersion
     */
    getArtifactVersion(input: GetArtifactVersionRequest, options?: RpcOptions): UnaryCall<GetArtifactVersionRequest, GetArtifactVersionResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetArtifactVersionRequest, GetArtifactVersionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetArtifactAsset returns the contents of a specific asset file.
     *
     * @generated from protobuf rpc: GetArtifactAsset
     */
    getArtifactAsset(input: GetArtifactAssetRequest, options?: RpcOptions): UnaryCall<GetArtifactAssetRequest, GetArtifactAssetResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetArtifactAssetRequest, GetArtifactAssetResponse>("unary", this._transport, method, opt, input);
    }
    // --- Publishing ---

    /**
     * PublishVersion publishes a new version of a schema or plugin.
     *
     * @generated from protobuf rpc: PublishVersion
     */
    publishVersion(input: PublishVersionRequest, options?: RpcOptions): UnaryCall<PublishVersionRequest, PublishVersionResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<PublishVersionRequest, PublishVersionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RevokeVersion marks a published version as revoked.
     *
     * @generated from protobuf rpc: RevokeVersion
     */
    revokeVersion(input: RevokeVersionRequest, options?: RpcOptions): UnaryCall<RevokeVersionRequest, RevokeVersionResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeVersionRequest, RevokeVersionResponse>("unary", this._transport, method, opt, input);
    }
    // --- Deploy key management ---

    /**
     * RegisterDeployKey registers a new deploy key for the authenticated user.
     *
     * @generated from protobuf rpc: RegisterDeployKey
     */
    registerDeployKey(input: RegisterDeployKeyRequest, options?: RpcOptions): UnaryCall<RegisterDeployKeyRequest, RegisterDeployKeyResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterDeployKeyRequest, RegisterDeployKeyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListDeployKeys lists registered deploy keys.
     *
     * @generated from protobuf rpc: ListDeployKeys
     */
    listDeployKeys(input: ListDeployKeysRequest, options?: RpcOptions): UnaryCall<ListDeployKeysRequest, ListDeployKeysResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDeployKeysRequest, ListDeployKeysResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ApproveDeployKey approves a deploy key for publishing.
     *
     * @generated from protobuf rpc: ApproveDeployKey
     */
    approveDeployKey(input: ApproveDeployKeyRequest, options?: RpcOptions): UnaryCall<ApproveDeployKeyRequest, ApproveDeployKeyResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ApproveDeployKeyRequest, ApproveDeployKeyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RevokeDeployKey revokes a deploy key.
     *
     * @generated from protobuf rpc: RevokeDeployKey
     */
    revokeDeployKey(input: RevokeDeployKeyRequest, options?: RpcOptions): UnaryCall<RevokeDeployKeyRequest, RevokeDeployKeyResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeDeployKeyRequest, RevokeDeployKeyResponse>("unary", this._transport, method, opt, input);
    }
    // --- Artifact permissions ---

    /**
     * AddAllowedSAN adds a cosign SAN pattern allowed to publish an artifact.
     *
     * @generated from protobuf rpc: AddAllowedSAN
     */
    addAllowedSAN(input: AddAllowedSANRequest, options?: RpcOptions): UnaryCall<AddAllowedSANRequest, AddAllowedSANResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddAllowedSANRequest, AddAllowedSANResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RemoveAllowedSAN removes an allowed SAN pattern from an artifact.
     *
     * @generated from protobuf rpc: RemoveAllowedSAN
     */
    removeAllowedSAN(input: RemoveAllowedSANRequest, options?: RpcOptions): UnaryCall<RemoveAllowedSANRequest, RemoveAllowedSANResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveAllowedSANRequest, RemoveAllowedSANResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * AddAllowedDeployKey adds a deploy key allowed to publish an artifact.
     *
     * @generated from protobuf rpc: AddAllowedDeployKey
     */
    addAllowedDeployKey(input: AddAllowedDeployKeyRequest, options?: RpcOptions): UnaryCall<AddAllowedDeployKeyRequest, AddAllowedDeployKeyResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddAllowedDeployKeyRequest, AddAllowedDeployKeyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RemoveAllowedDeployKey removes a deploy key from an artifact's allow list.
     *
     * @generated from protobuf rpc: RemoveAllowedDeployKey
     */
    removeAllowedDeployKey(input: RemoveAllowedDeployKeyRequest, options?: RpcOptions): UnaryCall<RemoveAllowedDeployKeyRequest, RemoveAllowedDeployKeyResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveAllowedDeployKeyRequest, RemoveAllowedDeployKeyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListArtifactPermissions lists the SANs and deploy keys allowed for an artifact.
     *
     * @generated from protobuf rpc: ListArtifactPermissions
     */
    listArtifactPermissions(input: ListArtifactPermissionsRequest, options?: RpcOptions): UnaryCall<ListArtifactPermissionsRequest, ListArtifactPermissionsResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListArtifactPermissionsRequest, ListArtifactPermissionsResponse>("unary", this._transport, method, opt, input);
    }
    // --- Visibility ---

    /**
     * SetArtifactVisibility sets whether an artifact is publicly visible.
     *
     * @generated from protobuf rpc: SetArtifactVisibility
     */
    setArtifactVisibility(input: SetArtifactVisibilityRequest, options?: RpcOptions): UnaryCall<SetArtifactVisibilityRequest, SetArtifactVisibilityResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetArtifactVisibilityRequest, SetArtifactVisibilityResponse>("unary", this._transport, method, opt, input);
    }
    // --- GitHub organisation management ---

    /**
     * AddGitHubOrg links a GitHub organisation to a hub organisation.
     *
     * @generated from protobuf rpc: AddGitHubOrg
     */
    addGitHubOrg(input: AddGitHubOrgRequest, options?: RpcOptions): UnaryCall<AddGitHubOrgRequest, AddGitHubOrgResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddGitHubOrgRequest, AddGitHubOrgResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * RemoveGitHubOrg removes a GitHub organisation mapping.
     *
     * @generated from protobuf rpc: RemoveGitHubOrg
     */
    removeGitHubOrg(input: RemoveGitHubOrgRequest, options?: RpcOptions): UnaryCall<RemoveGitHubOrgRequest, RemoveGitHubOrgResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveGitHubOrgRequest, RemoveGitHubOrgResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListGitHubOrgs lists all GitHub organisation mappings.
     *
     * @generated from protobuf rpc: ListGitHubOrgs
     */
    listGitHubOrgs(input: ListGitHubOrgsRequest, options?: RpcOptions): UnaryCall<ListGitHubOrgsRequest, ListGitHubOrgsResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListGitHubOrgsRequest, ListGitHubOrgsResponse>("unary", this._transport, method, opt, input);
    }
}
